// Keep actor instances in separate folder, under each actor.

const
    YOUNG_BENNETT = 'youngBennett',
    PRETEEN_BENNETT = 'preteenBennett',
    BENNETT = 'bennett',
    BENNETT_LIZ = 'bennettLiz',
    BENNETT_STEPHANIE = 'bennettStephanie',
    BENNETTS_CHRISTOPHER_LIZ = 'bennettsChristopherLiz',
    OLD_BENNETT = 'oldBennett',

    ANITA = 'anita',
    ANITA_BENNETT = 'anitaBennett',
    ESTHER = 'esther',
    ESTHER_MOTHER = 'estherMother',

    WILLY = 'willy',
    MOTHER = 'mother',
    FATHER = 'father',
    CHRISTOPHER = 'christopher',
    CHRISTOPHER_BENNETT = 'christopherBennett',

    SASHA = 'sasha',
    SASHA_BENNETT = 'sashaBennett',
    BRAD = 'brad',
    BRAD_BENNETT = 'bradBennett',
    BRAD_SASHA = 'bradSasha',
    ANDREW = 'andrew',

    CATHERINE = 'catherine',

    MARA = 'mara',
    JACOB = 'jacob',
    JACOB_MARA = 'jacobMara',
    ANA = 'ana',
    ANA_HOWIE = 'anaHowie',

    HOWIE = 'howie',
    TOMER = 'tomer',

    LIZ = 'liz',
    KHARI = 'khari',
    KHARI_LIZ = 'khariLiz',

    MIRIAM = 'miriam',
    MIRIAM_BENNETT = 'miriamBennett',
    MIRIAM_STEPHANIE = 'miriamStephanie',
    MIRIAM_TRISTAN = 'miriamTristan',
    TRISTAN = 'tristan',
    NESTOR = 'nestor',

    AMY = 'amy',
    AMY_STEPHANIE = 'amyStephanie',
    AMY_NESTOR_TOMER = 'amyNestorTomer',
    STEPHANIE = 'stephanie',
    WADE = 'wade',

    BENNETT_REFLECTION = 'bennettReflection',
    BENNETT_LIZ_REFLECTION = 'bennettLizReflection',
    LIZ_REFLECTION = 'lizReflection',
    KHARI_LIZ_REFLECTION = 'khariLizReflection'

export {
    YOUNG_BENNETT,
    PRETEEN_BENNETT,
    BENNETT,
    BENNETT_LIZ,
    BENNETT_STEPHANIE,
    BENNETTS_CHRISTOPHER_LIZ,
    OLD_BENNETT,
    ANITA,
    ANITA_BENNETT,
    ESTHER,
    ESTHER_MOTHER,
    WILLY,
    MOTHER,
    FATHER,
    CHRISTOPHER,
    CHRISTOPHER_BENNETT,
    SASHA,
    SASHA_BENNETT,
    BRAD,
    BRAD_BENNETT,
    BRAD_SASHA,
    ANDREW,
    CATHERINE,
    MARA,
    JACOB,
    JACOB_MARA,
    ANA,
    ANA_HOWIE,
    HOWIE,
    TOMER,
    LIZ,
    KHARI,
    KHARI_LIZ,
    MIRIAM,
    MIRIAM_BENNETT,
    MIRIAM_STEPHANIE,
    MIRIAM_TRISTAN,
    TRISTAN,
    NESTOR,
    AMY,
    AMY_STEPHANIE,
    AMY_NESTOR_TOMER,
    STEPHANIE,
    WADE,

    BENNETT_REFLECTION,
    BENNETT_LIZ_REFLECTION,
    LIZ_REFLECTION,
    KHARI_LIZ_REFLECTION
}
