// Keep actor instances in separate folder, under each actor.
export const YOUNG_BENNETT = 'youngBennett'
export const PRETEEN_BENNETT = 'preteenBennett'
export const BENNETT = 'bennett'
export const BENNETT_FATHER = 'bennettFather'
export const BENNETT_LIZ = 'bennettLiz'
export const BENNETT_STEPHANIE = 'bennettStephanie'
export const BENNETTS_CHRISTOPHER_LIZ = 'bennettsChristopherLiz'
export const OLD_BENNETT = 'oldBennett'

export const ANITA = 'anita'
export const ANITA_BENNETT = 'anitaBennett'
export const ESTHER = 'esther'
export const ESTHER_MOTHER = 'estherMother'

export const WILLY = 'willy'
export const MOTHER = 'mother'
export const FATHER = 'father'
export const CHRISTOPHER = 'christopher'
export const CHRISTOPHER_BENNETT = 'christopherBennett'
export const CHRISTOPHER_BENNETT_WILLY = 'christopherBennettWilly'

export const SASHA = 'sasha'
export const SASHA_BENNETT = 'sashaBennett'
export const BRAD = 'brad'
export const BRAD_BENNETT = 'bradBennett'
export const BRAD_SASHA = 'bradSasha'
export const ANDREW = 'andrew'

export const CATHERINE = 'catherine'

export const MARA = 'mara'
export const JACOB = 'jacob'
export const JACOB_MARA = 'jacobMara'
export const ANA = 'ana'
export const ANA_HOWIE = 'anaHowie'

export const HOWIE = 'howie'
export const HOWIE_WILLY = 'howieWilly'
export const TOMER = 'tomer'

export const LIZ = 'liz'
export const KHARI = 'khari'
export const KHARI_LIZ = 'khariLiz'

export const MIRIAM = 'miriam'
export const MIRIAM_BENNETT = 'miriamBennett'
export const MIRIAM_STEPHANIE = 'miriamStephanie'
export const MIRIAM_TRISTAN = 'miriamTristan'
export const TRISTAN = 'tristan'
export const NESTOR = 'nestor'

export const AMY = 'amy'
export const AMY_STEPHANIE = 'amyStephanie'
export const AMY_NESTOR_TOMER = 'amyNestorTomer'
export const STEPHANIE = 'stephanie'
export const WADE = 'wade'

export const BENNETT_REFLECTION = 'bennettReflection'
export const BENNETT_LIZ_REFLECTION = 'bennettLizReflection'
export const LIZ_REFLECTION = 'lizReflection'
export const KHARI_LIZ_REFLECTION = 'khariLizReflection'
