const
    NOHO_HOUSES_BACKDROP = 'nohoHousesBackdrop',
    NOHO_SCHOOL_BACKDROP = 'nohoSchoolBackdrop',
    VALLEY_BACKDROP = 'valleyBackdrop',
    BEDROOM_BACKDROP = 'bedroomBackdrop',
    BEDROOM_SIREN_BACKDROP = 'bedroomSirenBackdrop',
    TAIWAN_MOUNTAINS_FAR = 'taiwanMountainsFar',
    SCHOOLBUS_THOUGHT_BACKDROP = 'schoolbusThoughtBackdrop',
    VAN_NUYS_THOUGHT_BACKDROP = 'vanNuysThoughtBackdrop',
    TAIWAN_STREETS_BACKDROP = 'taiwanStreetsBackdrop',
    SHORE_RICKSHAW_BACKDROP = 'shoreRickshawBackdrop',
    SHORE_BUOY_BACKDROP = 'shoreBuoyBackdrop',
    OCEAN_BUOY_BACKDROP = 'oceanBuoyBackdrop',
    OCEAN_DEPTHS_BACKDROP = 'oceanDepthsBackdrop',
    OCEAN_FLOOR_BACKDROP = 'oceanFloorBackdrop',
    BEDROOM_BUS_BACKDROP = 'bedroomBusBackdrop',
    VAN_NUYS_SCHOOL_BACKDROP = 'vanNuysSchoolBackdrop',
    BENNETT_COUCH_THOUGHT_BACKDROP = 'bennettCouchThoughtBackdrop',
    WEST_BERKELEY_BACKDROP = 'westBerkeleyBackdrop',
    UC_BERKELEY_BACKDROP = 'ucBerkeleyBackdrop',
    BAY_AREA_BACKDROP = 'bayAreaBackdrop',
    GO_KART_THOUGHT = 'goKartThought',
    UCLA_BACKDROP = 'uclaBackdrop',
    PHARMACY_THOUGHT = 'pharmacyThought',
    CEMETERY_HILLS_FAR = 'cemeteryHillsFar',
    LOS_ANGELES_BACKDROP = 'losAngelesBackdrop',
    OAKLAND_BACKDROP = 'oaklandBackdrop',
    LIZ_COUCH_THOUGHT = 'lizCouchThought',
    RESIDENCE_BACKDROP = 'residenceBackdrop',
    COMMERCIAL_BACKDROP = 'commercialBackdrop',
    PUBLIC_BACKDROP = 'publicBackdrop',
    EL_CERRITO_BACKDROP = 'elCerritoBackdrop',
    PAMPAS_BACKDROP = 'pampasBackdrop',
    WEDDING_BACKDROP = 'weddingBackdrop',
    CLIFF_BACKDROP = 'cliffBackdrop',
    CLIFF_GRAVES_BACKDROP = 'cliffGravesBackdrop',
    INVERSE_THOUGHT = 'inverseThought'

export {
    NOHO_HOUSES_BACKDROP,
    NOHO_SCHOOL_BACKDROP,
    VALLEY_BACKDROP,
    BEDROOM_BACKDROP,
    BEDROOM_SIREN_BACKDROP,
    TAIWAN_MOUNTAINS_FAR,
    SCHOOLBUS_THOUGHT_BACKDROP,
    VAN_NUYS_THOUGHT_BACKDROP,
    TAIWAN_STREETS_BACKDROP,
    SHORE_RICKSHAW_BACKDROP,
    SHORE_BUOY_BACKDROP,
    OCEAN_BUOY_BACKDROP,
    OCEAN_DEPTHS_BACKDROP,
    OCEAN_FLOOR_BACKDROP,
    BEDROOM_BUS_BACKDROP,
    VAN_NUYS_SCHOOL_BACKDROP,
    BENNETT_COUCH_THOUGHT_BACKDROP,
    WEST_BERKELEY_BACKDROP,
    UC_BERKELEY_BACKDROP,
    BAY_AREA_BACKDROP,
    GO_KART_THOUGHT,
    UCLA_BACKDROP,
    PHARMACY_THOUGHT,
    CEMETERY_HILLS_FAR,
    LOS_ANGELES_BACKDROP,
    OAKLAND_BACKDROP,
    LIZ_COUCH_THOUGHT,
    RESIDENCE_BACKDROP,
    COMMERCIAL_BACKDROP,
    PUBLIC_BACKDROP,
    EL_CERRITO_BACKDROP,
    PAMPAS_BACKDROP,
    WEDDING_BACKDROP,
    CLIFF_BACKDROP,
    CLIFF_GRAVES_BACKDROP,
    INVERSE_THOUGHT
}
