const
    DEFAULT_STAGE_KEY = 'defaultStage',
    LOGUE_KEY = 'logue',

    NOHO_HOUSES_KEY = 'nohoHouses',
    NOHO_SCHOOL_KEY = 'nohoSchool',
    FAMILY_BATHROOM_KEY = 'familyBathroom',
    FAMILY_BATHROOM_OPEN_KEY = 'familyBathroomOpen',

    FREEWAY_KEY = 'freeway',
    PORCH_KEY = 'porch',
    CHANGELING_CAVE_KEY = 'changelingCave',

    PUPPET_SHOW_KEY = 'puppetShow',
    SCHOOLBUS_KEY = 'schoolbus',
    TETHERBALL_COURT_KEY = 'tetherballCourt',

    TAIWAN_ROOM_KEY = 'taiwanRoom',
    TAIWAN_STAIRS_KEY = 'taiwanStairs',
    TAIWAN_GATE_KEY = 'taiwanGate',
    RICKSHAW_KEY = 'rickshaw',
    SHORE_KEY = 'shore',
    BUOY_KEY = 'buoy',
    OCEAN_DEPTHS_KEY = 'oceanDepths',
    OCEAN_FLOOR_KEY = 'oceanFloor',

    BEDROOM_KEY = 'bedroom',
    BEDROOM_STOOL_KEY = 'bedroomStool',
    BEDROOM_OPEN_KEY = 'bedroomOpen',
    BEDROOM_DOGS_KEY = 'bedroomDogs',
    BEDROOM_SPACE_KEY = 'bedroomSpace',

    VAN_NUYS_LOCKERS_KEY = 'vanNuysLockers',
    VAN_NUYS_QUAD_KEY = 'vanNuysQuad',
    VAN_NUYS_HALLWAY_KEY = 'vanNuysHallway',

    CATHOLIC_CHURCH_KEY = 'catholicChurch',
    BANCROFT_LIBRARY_KEY = 'bancroftLibrary',
    CAMPANILE_KEY = 'campanile',

    CINEMA_KEY = 'cinema',
    CINEMA_STREET_KEY = 'cinemaStreet',

    BASEMENT_KEY = 'basement',
    BASEMENT_BED_KEY = 'basementBed',

    MUSEUM_KEY = 'museum',
    BACKSTAGE_KEY = 'backstage',
    GO_KARTS_KEY = 'goKarts',

    DISHROOM_KEY = 'dishroom',
    WAITING_ROOM_KEY = 'waitingRoom',

    CLUB_FRONT_KEY = 'clubFront',
    CLUB_FRONT_FAR_KEY = 'clubFrontFar',
    CLUB_SIDE_CROWD_KEY = 'clubSideCrowd',
    CLUB_SIDE_STAGE_KEY = 'clubSideStage',
    CLUB_LOADING = 'clubLoading',

    BENNETT_BED_KEY = 'bennettBed',
    BENNETT_COUCH_KEY = 'bennettCouch',
    BENNETT_COUCH_THOUGHT_KEY = 'bennettCouchThought',
    BENNETT_COURTYARD_KEY = 'bennettCourtyard',
    BENNETT_GATE_KEY = 'bennettGate',

    LIZ_BED_KEY = 'lizBed',
    LIZ_COUCH_KEY = 'lizCouch',
    LIZ_COUCH_THOUGHT_KEY = 'lizCouchThought',
    LIZ_GATE_KEY = 'lizGate',
    LIZ_GATE_STREET_KEY = 'lizGateStreet',

    ROYCE_HALL_KEY = 'royceHall',
    WALGREENS_KEY = 'walgreens',
    STEAM_TUNNEL_KEY = 'steamTunnel',
    CEMETERY_KEY = 'cemetery',
    STATION_WAGON_KEY = 'stationWagon',
    ATTIC_KEY = 'attic',

    OAKLAND_HOUSES_KEY = 'oaklandHouses',
    OAKLAND_RESIDENTIAL_KEY = 'oaklandResidential',
    OAKLAND_COMMERCIAL_KEY = 'oaklandCommercial',
    OAKLAND_PUBLIC_KEY = 'oaklandPublic',

    SNOWGLOBES_PAST_KEY = 'snowglobesPast',
    SNOWGLOBES_PRESENT_KEY = 'snowglobesPresent',
    SNOWGLOBES_FUTURE_KEY = 'snowglobesFuture',

    EL_CERRITO_KEY = 'elCerrito',
    EL_CERRITO_CAR_KEY = 'elCerritoCar',
    EL_CERRITO_DEATHBED_KEY = 'elCerritoDeathbed',
    EL_CERRITO_TENNIS_KEY = 'elCerritoTennis',

    ALLEY_KEY = 'alley',

    EL_TORITO_KEY = 'elTorito',
    PAMPAS_KEY = 'pampas',
    OUTDOOR_WEDDING_KEY = 'outdoorWedding',
    CLIFF_KEY = 'cliff',
    CLIFF_DEATHBED_KEY = 'cliffDeathbed'

export {
    DEFAULT_STAGE_KEY,
    LOGUE_KEY,
    NOHO_HOUSES_KEY,
    NOHO_SCHOOL_KEY,
    FAMILY_BATHROOM_KEY,
    FAMILY_BATHROOM_OPEN_KEY,
    FREEWAY_KEY,
    PORCH_KEY,
    CHANGELING_CAVE_KEY,
    PUPPET_SHOW_KEY,
    SCHOOLBUS_KEY,
    TETHERBALL_COURT_KEY,
    TAIWAN_ROOM_KEY,
    TAIWAN_STAIRS_KEY,
    TAIWAN_GATE_KEY,
    RICKSHAW_KEY,
    SHORE_KEY,
    BUOY_KEY,
    OCEAN_DEPTHS_KEY,
    OCEAN_FLOOR_KEY,
    BEDROOM_KEY,
    BEDROOM_STOOL_KEY,
    BEDROOM_OPEN_KEY,
    BEDROOM_DOGS_KEY,
    BEDROOM_SPACE_KEY,
    VAN_NUYS_LOCKERS_KEY,
    VAN_NUYS_QUAD_KEY,
    VAN_NUYS_HALLWAY_KEY,
    CATHOLIC_CHURCH_KEY,
    BANCROFT_LIBRARY_KEY,
    CAMPANILE_KEY,
    CINEMA_KEY,
    CINEMA_STREET_KEY,
    BASEMENT_KEY,
    BASEMENT_BED_KEY,
    MUSEUM_KEY,
    BACKSTAGE_KEY,
    GO_KARTS_KEY,
    DISHROOM_KEY,
    WAITING_ROOM_KEY,
    CLUB_FRONT_KEY,
    CLUB_FRONT_FAR_KEY,
    CLUB_SIDE_CROWD_KEY,
    CLUB_SIDE_STAGE_KEY,
    CLUB_LOADING,
    BENNETT_BED_KEY,
    BENNETT_COUCH_KEY,
    BENNETT_COUCH_THOUGHT_KEY,
    BENNETT_COURTYARD_KEY,
    BENNETT_GATE_KEY,
    LIZ_BED_KEY,
    LIZ_COUCH_KEY,
    LIZ_COUCH_THOUGHT_KEY,
    LIZ_GATE_KEY,
    LIZ_GATE_STREET_KEY,
    ROYCE_HALL_KEY,
    WALGREENS_KEY,
    STEAM_TUNNEL_KEY,
    CEMETERY_KEY,
    STATION_WAGON_KEY,
    ATTIC_KEY,
    OAKLAND_HOUSES_KEY,
    OAKLAND_RESIDENTIAL_KEY,
    OAKLAND_COMMERCIAL_KEY,
    OAKLAND_PUBLIC_KEY,
    SNOWGLOBES_PAST_KEY,
    SNOWGLOBES_PRESENT_KEY,
    SNOWGLOBES_FUTURE_KEY,
    EL_CERRITO_KEY,
    EL_CERRITO_CAR_KEY,
    EL_CERRITO_DEATHBED_KEY,
    EL_CERRITO_TENNIS_KEY,
    ALLEY_KEY,
    EL_TORITO_KEY,
    PAMPAS_KEY,
    OUTDOOR_WEDDING_KEY,
    CLIFF_KEY,
    CLIFF_DEATHBED_KEY
}
