// Keep cutout instances in this file.

const
    FIRE_HYDRANT = 'fireHydrant',
    PLAYGROUND_SLIDE = 'playgroundSlide',
    BATHTUB = 'bathtub',
    MIRRORED_SINK = 'mirroredSink',
    TOWEL_RACK = 'towelRack',
    OVERPASS_SIGN_FRONT = 'overpassSignFront',
    OVERPASS_SIGN_BACK = 'overpassSignBack',
    PORCH_PLANTS_LEFT = 'porchPlantsLeft',
    PORCH_PLANTS_RIGHT = 'porchPlantsRight',
    TROLL_SHADOW_LEFT = 'trollShadowLeft',
    TROLL_SHADOW_RIGHT = 'trollShadowRight',
    CAMPFIRE = 'campfire',
    SCHOOLBUS_FRONT = 'schoolbusFront',
    SCHOOLBUS_BACK = 'schoolbusBack',
    BUDDHA_SHRINE = 'buddhaShrine',
    TAIWAN_FRIDGE_FRONT = 'taiwanFridgeFront',
    BENNETT_TAIWAN_STAIRS = 'bennettTaiwanStairs',
    ODIN_TAIWAN_STAIRS = 'odinTaiwanStairs',
    TAIWAN_FRIDGE_SIDE = 'taiwanFridgeSide',
    BENNETT_TAIWAN_GATE = 'bennettTaiwanGate',
    ODIN_TAIWAN_GATE = 'odinTaiwanGate',
    BENNETT_ODIN_RICKSHAW = 'bennettOdinRickshaw',
    BENNETT_SHORE = 'bennettShore',
    ODIN_SHORE = 'odinShore',
    BENNETT_ODIN_BUOY = 'bennettOdinBuoy',
    YELLOW_TAPED_GRILL = 'yellowTapedGrill',
    BENNETT_ODIN_DEPTHS = 'bennettOdinDepths',
    SEA_SERPENTS = 'seaSerpents',
    BENNETT_OCEAN_FLOOR = 'bennettOceanFloor',
    ODIN_OCEAN_FLOOR = 'odinOceanFloor',
    BENNETT_MAT = 'bennettMat',
    ODIN_MAT = 'odinMat',
    BUDDHA_CAVE = 'buddhaCave',
    LOCKER_BANK = 'lockerBank',
    TRASH_CAN_BACK = 'trashCanBack',
    VAN_NUYS_PLANTS_BACK = 'vanNuysPlantsBack',
    TRASH_CAN_FRONT = 'trashCanFront',
    VAN_NUYS_PLANTS_FRONT = 'vanNuysPlantsFront',
    VAN_NUYS_LOGO = 'vanNuysLogo'

export {
    FIRE_HYDRANT,
    PLAYGROUND_SLIDE,
    BATHTUB,
    MIRRORED_SINK,
    TOWEL_RACK,
    OVERPASS_SIGN_FRONT,
    OVERPASS_SIGN_BACK,
    PORCH_PLANTS_LEFT,
    PORCH_PLANTS_RIGHT,
    TROLL_SHADOW_LEFT,
    TROLL_SHADOW_RIGHT,
    CAMPFIRE,
    SCHOOLBUS_FRONT,
    SCHOOLBUS_BACK,
    BUDDHA_SHRINE,
    TAIWAN_FRIDGE_FRONT,
    BENNETT_TAIWAN_STAIRS,
    ODIN_TAIWAN_STAIRS,
    TAIWAN_FRIDGE_SIDE,
    BENNETT_TAIWAN_GATE,
    ODIN_TAIWAN_GATE,
    BENNETT_ODIN_RICKSHAW,
    BENNETT_SHORE,
    ODIN_SHORE,
    BENNETT_ODIN_BUOY,
    YELLOW_TAPED_GRILL,
    BENNETT_ODIN_DEPTHS,
    SEA_SERPENTS,
    BENNETT_OCEAN_FLOOR,
    ODIN_OCEAN_FLOOR,
    BENNETT_MAT,
    ODIN_MAT,
    BUDDHA_CAVE,
    LOCKER_BANK,
    TRASH_CAN_BACK,
    VAN_NUYS_PLANTS_BACK,
    TRASH_CAN_FRONT,
    VAN_NUYS_PLANTS_FRONT,
    VAN_NUYS_LOGO
}
