// Keep cutout instances in this file.

const
    FIRE_HYDRANT = 'fireHydrant',
    PLAYGROUND_SLIDE = 'playgroundSlide',
    BATHTUB = 'bathtub',
    MIRRORED_SINK = 'mirroredSink',
    TOWEL_RACK = 'towelRack',
    OVERPASS_SIGN_FRONT = 'overpassSignFront',
    OVERPASS_SIGN_BACK = 'overpassSignBack',
    PORCH_PLANTS_LEFT = 'porchPlantsLeft',
    PORCH_PLANTS_RIGHT = 'porchPlantsRight',
    CAPTAIN_BED_DRAWERS = 'captainBedDrawers',
    TROLL_SHADOW_LEFT = 'trollShadowLeft',
    TROLL_SHADOW_RIGHT = 'trollShadowRight',
    CAMPFIRE = 'campfire',
    STALACTITES = 'stalactites',
    SCHOOLBUS_FRONT = 'schoolbusFront',
    SCHOOLBUS_BACK = 'schoolbusBack',
    BUDDHA_SHRINE = 'buddhaShrine',
    TAIWAN_FRIDGE_FRONT = 'taiwanFridgeFront',
    BENNETT_TAIWAN_STAIRS = 'bennettTaiwanStairs',
    ODIN_TAIWAN_STAIRS = 'odinTaiwanStairs',
    TAIWAN_FRIDGE_SIDE = 'taiwanFridgeSide',
    BENNETT_TAIWAN_GATE = 'bennettTaiwanGate',
    ODIN_TAIWAN_GATE = 'odinTaiwanGate',
    BENNETT_ODIN_RICKSHAW = 'bennettOdinRickshaw',
    BENNETT_SHORE = 'bennettShore',
    ODIN_SHORE = 'odinShore',
    BENNETT_ODIN_BUOY = 'bennettOdinBuoy',
    YELLOW_TAPED_GRILL = 'yellowTapedGrill',
    BENNETT_ODIN_DEPTHS = 'bennettOdinDepths',
    SEA_SERPENTS = 'seaSerpents',
    BENNETT_OCEAN_FLOOR = 'bennettOceanFloor',
    ODIN_OCEAN_FLOOR = 'odinOceanFloor',
    BENNETT_MAT = 'bennettMat',
    ODIN_MAT = 'odinMat',
    BUDDHA_CAVE = 'buddhaCave',
    LOCKER_BANK = 'lockerBank',
    TRASH_CAN_BACK = 'trashCanBack',
    VAN_NUYS_PLANTS_BACK = 'vanNuysPlantsBack',
    TRASH_CAN_FRONT = 'trashCanFront',
    VAN_NUYS_PLANTS_FRONT = 'vanNuysPlantsFront',
    VAN_NUYS_LOGO = 'vanNuysLogo',
    RECYCLABLES = 'recyclables',
    NIRVANA_POSTER = 'nirvanaPoster',
    DISPENSER_LEFT = 'dispenserLeft',
    DISPENSER_RIGHT = 'dispenserRight',
    BERKELEY_LAMPPOST = 'berkeleyLamppost',
    SIGNPOST = 'signPost',
    BANCROFT_SHRUB_LEFT = 'bancroftShrubLeft',
    BANCROFT_SHRUB_RIGHT = 'bancroftShrubRight',
    UC_BERKELEY_TREE_LEFT = 'ucBerkeleyTreeLeft',
    UC_BERKELEY_TREE_RIGHT = 'ucBerkeleyTreeRight',
    LEONARD_COHEN_POSTER = 'leonardCohenPoster',
    MONITOR_SPEAKER_LEFT = 'monitorSpeakerLeft',
    MONITOR_SPEAKER_RIGHT = 'monitorSpeakerRight',
    WALL_SPEAKER_LEFT = 'wallSpeakerLeft',
    WALL_SPEAKER_RIGHT = 'wallSpeakerRight',
    CINEMA_POSTER_LEFT = 'cinemaPosterLeft',
    CINEMA_POSTER_RIGHT = 'cinemaPosterRight',
    SANDBAGS = 'sandbags',
    STAGE_LIGHTS = 'stageLights',
    GO_KART_LEFT = 'goKartLeft',
    GO_KART_RIGHT = 'goKartRight',
    TRAFFIC_LIGHT = 'trafficLight',
    DISHROOM_SINK = 'dishroomSink',
    APARTMENT_PLANT = 'apartmentPlant',
    CODE_BOX = 'codeBox',
    LIGHT_SWITCH = 'lightSwitch',
    CLIPBOARD = 'clipboard',
    PAINTING = 'painting',
    WAITING_ROOM_PLANT = 'waitingRoomPlant',
    STATION_WAGON_FRONT = 'stationWagonFront',
    STATION_WAGON_BACK = 'stationWagonBack',
    STORAGE_BOXES = 'storageBoxes',
    STORAGE_CHEST = 'storageChest',
    HOWIE_FRIDGE = 'howieFridge',
    TELEVISION = 'television',
    MONITOR_SPEAKER_SIDE = 'monitorSpeakerSide',
    WALL_SPEAKER_SIDE = 'wallSpeakerSide',
    CROWD_SIDE_NEAR = 'crowdSideNear',
    CROWD_SIDE_FAR = 'crowdSideFar',
    VOLKSWAGEN = 'volkswagen',
    CROWD_BACK_NEAR = 'crowdBackNear',
    CROWD_BACK_FAR = 'crowdBackFar',
    DUMPSTER = 'dumpster',
    WEDDING_PLATFORM = 'weddingPlatform',
    WEDDING_CROWD = 'weddingCrowd',
    IV_DRIP = 'ivDrip',

    ARRANGEMENT_CINEMA_POSTER = 'arrangementCinemaPoster',
    ARRANGEMENT_CINEMA_POSTER_STREET = 'arrangementCinemaPosterStreet',
    ARRANGEMENT_MONITOR_SIDE_CROWD = 'arrangementMonitorSideCrowd',
    ARRANGEMENT_MONITOR_SIDE_STAGE = 'arrangementMonitorSideStage',
    ARRANGEMENT_WALL_SIDE_CROWD = 'arrangementWallSideCrowd',
    ARRANGEMENT_WALL_SIDE_STAGE = 'arrangementWallSideStage'

export {
    FIRE_HYDRANT,
    PLAYGROUND_SLIDE,
    BATHTUB,
    MIRRORED_SINK,
    TOWEL_RACK,
    OVERPASS_SIGN_FRONT,
    OVERPASS_SIGN_BACK,
    PORCH_PLANTS_LEFT,
    PORCH_PLANTS_RIGHT,
    CAPTAIN_BED_DRAWERS,
    TROLL_SHADOW_LEFT,
    TROLL_SHADOW_RIGHT,
    CAMPFIRE,
    STALACTITES,
    SCHOOLBUS_FRONT,
    SCHOOLBUS_BACK,
    BUDDHA_SHRINE,
    TAIWAN_FRIDGE_FRONT,
    BENNETT_TAIWAN_STAIRS,
    ODIN_TAIWAN_STAIRS,
    TAIWAN_FRIDGE_SIDE,
    BENNETT_TAIWAN_GATE,
    ODIN_TAIWAN_GATE,
    BENNETT_ODIN_RICKSHAW,
    BENNETT_SHORE,
    ODIN_SHORE,
    BENNETT_ODIN_BUOY,
    YELLOW_TAPED_GRILL,
    BENNETT_ODIN_DEPTHS,
    SEA_SERPENTS,
    BENNETT_OCEAN_FLOOR,
    ODIN_OCEAN_FLOOR,
    BENNETT_MAT,
    ODIN_MAT,
    BUDDHA_CAVE,
    LOCKER_BANK,
    TRASH_CAN_BACK,
    VAN_NUYS_PLANTS_BACK,
    TRASH_CAN_FRONT,
    VAN_NUYS_PLANTS_FRONT,
    VAN_NUYS_LOGO,
    RECYCLABLES,
    NIRVANA_POSTER,
    DISPENSER_LEFT,
    DISPENSER_RIGHT,
    BERKELEY_LAMPPOST,
    SIGNPOST,
    BANCROFT_SHRUB_LEFT,
    BANCROFT_SHRUB_RIGHT,
    UC_BERKELEY_TREE_LEFT,
    UC_BERKELEY_TREE_RIGHT,
    LEONARD_COHEN_POSTER,
    MONITOR_SPEAKER_LEFT,
    MONITOR_SPEAKER_RIGHT,
    WALL_SPEAKER_LEFT,
    WALL_SPEAKER_RIGHT,
    CINEMA_POSTER_LEFT,
    CINEMA_POSTER_RIGHT,
    SANDBAGS,
    STAGE_LIGHTS,
    GO_KART_LEFT,
    GO_KART_RIGHT,
    TRAFFIC_LIGHT,
    DISHROOM_SINK,
    APARTMENT_PLANT,
    CODE_BOX,
    LIGHT_SWITCH,
    CLIPBOARD,
    PAINTING,
    WAITING_ROOM_PLANT,
    STATION_WAGON_FRONT,
    STATION_WAGON_BACK,
    STORAGE_BOXES,
    STORAGE_CHEST,
    HOWIE_FRIDGE,
    TELEVISION,
    MONITOR_SPEAKER_SIDE,
    WALL_SPEAKER_SIDE,
    CROWD_SIDE_NEAR,
    CROWD_SIDE_FAR,
    VOLKSWAGEN,
    CROWD_BACK_NEAR,
    CROWD_BACK_FAR,
    DUMPSTER,
    WEDDING_PLATFORM,
    WEDDING_CROWD,
    IV_DRIP,

    ARRANGEMENT_CINEMA_POSTER,
    ARRANGEMENT_CINEMA_POSTER_STREET,
    ARRANGEMENT_MONITOR_SIDE_CROWD,
    ARRANGEMENT_MONITOR_SIDE_STAGE,
    ARRANGEMENT_WALL_SIDE_CROWD,
    ARRANGEMENT_WALL_SIDE_STAGE
}
