const
    PORCH_DOOR = 'porchDoor',
    BEDROOM_BLINDS = 'bedroomBlinds',
    BEDROOM_BLINDS_OPEN = 'bedroomBlindsOpen',
    IRON_GATE_LOW = 'ironGateLow',
    IRON_GATE = 'ironGate',
    PRINCIPAL_DOOR = 'principalDoor',
    BENNETT_BLINDS = 'bennettBlinds',
    BENNETT_DOOR_OUTSIDE = 'bennettDoorOutside',
    BENNETT_GATE_SIDE = 'bennettGateSide',
    BANCROFT_DOOR = 'bancroftDoor',
    BASEMENT_DOOR = 'basementDoor',
    BASEMENT_DOOR_OPEN = 'basementDoorOpen',
    CINEMA_DOORS = 'cinemaDoors',
    LIZ_BLINDS = 'lizBlinds',
    LIZ_BLINDS_OPEN = 'lizBlindsOpen',
    LIZ_GATE_OUTSIDE = 'lizGateOutside',
    LIZ_GATE_OUTSIDE_OPEN = 'lizGateOutsideOpen',
    DISHROOM_DOOR = 'dishroomDoor',
    BENNETT_GATE_FRONT = 'bennettGateFront',
    BENNETT_BLINDS_OPEN = 'bennettBlindsOpen',
    BENNETT_GATE_SIDE_OPEN = 'bennettGateSideOpen',
    BENNETT_DOOR_INSIDE = 'bennettDoorInside',
    BENNETT_DOOR_INSIDE_OPEN = 'bennettDoorInsideOpen',
    WAITING_ROOM_DOOR = 'waitingRoomDoor',
    WAITING_ROOM_DOOR_OPEN = 'waitingRoomDoorOpen',
    CLUB_DOOR = 'clubDoor',
    LIZ_DOOR = 'lizDoor',
    LIZ_DOOR_OPEN = 'lizDoorOpen',
    LIZ_GATE_INSIDE = 'lizGateInside',
    LIZ_GATE_INSIDE_OPEN = 'lizGateInsideOpen',
    LOADING_DOCK_DOOR = 'loadingDockDoor',
    EL_TORITO_DOOR_LEFT = 'elToritoDoorLeft',
    EL_TORITO_DOOR_RIGHT = 'elToritoDoorRight',

    ARRANGEMENT_LIZ_BLINDS = 'arrangementLizBlinds',
    ARRANGEMENT_LIZ_BLINDS_STREET = 'arrangementLizBlindsStreet'

export {
    PORCH_DOOR,
    BEDROOM_BLINDS,
    BEDROOM_BLINDS_OPEN,
    IRON_GATE_LOW,
    IRON_GATE,
    PRINCIPAL_DOOR,
    BENNETT_BLINDS,
    BENNETT_DOOR_OUTSIDE,
    BENNETT_GATE_SIDE,
    BANCROFT_DOOR,
    BASEMENT_DOOR,
    BASEMENT_DOOR_OPEN,
    CINEMA_DOORS,
    LIZ_BLINDS,
    LIZ_BLINDS_OPEN,
    LIZ_GATE_OUTSIDE,
    LIZ_GATE_OUTSIDE_OPEN,
    DISHROOM_DOOR,
    BENNETT_BLINDS_OPEN,
    BENNETT_GATE_FRONT,
    BENNETT_GATE_SIDE_OPEN,
    BENNETT_DOOR_INSIDE,
    BENNETT_DOOR_INSIDE_OPEN,
    WAITING_ROOM_DOOR,
    WAITING_ROOM_DOOR_OPEN,
    CLUB_DOOR,
    LIZ_DOOR,
    LIZ_DOOR_OPEN,
    LIZ_GATE_INSIDE,
    LIZ_GATE_INSIDE_OPEN,
    LOADING_DOCK_DOOR,
    EL_TORITO_DOOR_LEFT,
    EL_TORITO_DOOR_RIGHT,

    ARRANGEMENT_LIZ_BLINDS,
    ARRANGEMENT_LIZ_BLINDS_STREET
}
