// Keep fixtures instances in this file.

const
    PLAYGROUND_BALL = 'playgroundBall',
    RECORD_PLAYER_STOOL = 'recordPlayerStool',
    SHOPPING_CART = 'shoppingCart',
    CHRISTOPHER_LETTERS = 'christopherLetters',
    BACKPACK_BENNETT = 'backpackBennett',
    BACKPACK_SASHA = 'backpackSasha',
    FRIDGE_DRAWINGS = 'fridgeDrawings',
    BENNETT_LETTERS = 'bennettLetters',
    CAPTAIN_BED_LAMP = 'captainBedLamp',
    THROWN_FRUIT = 'thrownFruit',
    BENNETT_RECORD_PLAYER = 'bennettRecordPlayer',
    BENNETT_COUCH_LAMP = 'bennettCouchLamp',
    MICROPHONE_STAND = 'microphoneStand',
    ALBUMS_MILK_CRATE = 'albumsMilkCrate',
    BASS_CASE_OPEN = 'bassCaseOpen',
    DRUMKIT = 'drumKit',
    BASS_CASE = 'bassCase',
    GUITAR_CASE = 'guitarCase',
    CAVEMAN_BONES = 'cavemanBones',
    PUSH_BROOM = 'pushBroom',
    STEPLADDER = 'stepladder',
    MANNEQUIN = 'mannequin',
    CONVEYOR_BELT = 'conveyorBelt',
    GLASS_CART = 'glassCart',
    TRAY_CART = 'trayCart',
    GLASS_RACK = 'glassRack',
    TRAY_RACK = 'trayRack',
    DISH_PILE = 'dishPile',
    NUDE_DRAWINGS = 'nudeDrawings',
    VASELINE = 'vaseline',
    CEILING_MIRROR = 'ceilingMirror',
    LIZ_NIGHTSTAND = 'lizNightstand',
    LIZ_NIGHTSTAND_REFLECTION = 'lizNightstandReflection',
    LIZ_PHONE = 'lizPhone',
    LIZ_PHONE_BASE = 'lizPhoneBase',
    LIZ_PHONE_REFLECTION = 'lizPhoneReflection',
    LIZ_PHONE_BASE_REFLECTION = 'lizPhoneBaseReflection',
    GRAVESTONE = 'gravestone',
    EVIAN_BOTTLES = 'evianBottles',
    GUITAR_STAND = 'guitarStand',
    GUITAR_AMP = 'guitarAmp',
    DRUMS_STACKED = 'drumsStacked',
    BASS_AMP = 'bassAmp',
    RECORDING_CONSOLE = 'recordingConsole',
    RECORDING_MIC = 'recordingMic',
    RECORDING_BEERS = 'recordingBeers',
    BURGER_WRAPPER = 'burgerWrapper',
    HOSPITAL_RECORD_PLAYER = 'hospitalRecordPlayer'

export {
    PLAYGROUND_BALL,
    RECORD_PLAYER_STOOL,
    SHOPPING_CART,
    CHRISTOPHER_LETTERS,
    BACKPACK_BENNETT,
    BACKPACK_SASHA,
    FRIDGE_DRAWINGS,
    BENNETT_LETTERS,
    CAPTAIN_BED_LAMP,
    THROWN_FRUIT,
    BENNETT_RECORD_PLAYER,
    BENNETT_COUCH_LAMP,
    MICROPHONE_STAND,
    ALBUMS_MILK_CRATE,
    BASS_CASE_OPEN,
    DRUMKIT,
    BASS_CASE,
    GUITAR_CASE,
    CAVEMAN_BONES,
    PUSH_BROOM,
    STEPLADDER,
    MANNEQUIN,
    CONVEYOR_BELT,
    GLASS_CART,
    TRAY_CART,
    GLASS_RACK,
    TRAY_RACK,
    DISH_PILE,
    NUDE_DRAWINGS,
    VASELINE,
    CEILING_MIRROR,
    LIZ_NIGHTSTAND,
    LIZ_NIGHTSTAND_REFLECTION,
    LIZ_PHONE,
    LIZ_PHONE_BASE,
    LIZ_PHONE_REFLECTION,
    LIZ_PHONE_BASE_REFLECTION,
    GRAVESTONE,
    EVIAN_BOTTLES,
    GUITAR_STAND,
    GUITAR_AMP,
    DRUMS_STACKED,
    BASS_AMP,
    RECORDING_CONSOLE,
    RECORDING_MIC,
    RECORDING_BEERS,
    BURGER_WRAPPER,
    HOSPITAL_RECORD_PLAYER
}
