// Keep fixtures instances in this file.

const
    PLAYGROUND_BALL = 'playgroundBall',
    RECORD_PLAYER_STOOL = 'recordPlayerStool',
    SHOPPING_CART = 'shoppingCart',
    CHRISTOPHER_LETTERS = 'christopherLetters',
    BACKPACK_BENNETT = 'backpackBennett',
    BACKPACK_SASHA = 'backpackSasha',
    FRIDGE_DRAWINGS = 'fridgeDrawings',
    BENNETT_LETTERS = 'bennettLetters',
    CAPTAIN_BED_LAMP = 'captainBedLamp',
    THROWN_FRUIT = 'thrownFruit',
    BENNETT_RECORD_PLAYER = 'bennettRecordPlayer',
    BENNETT_COUCH_LAMP = 'bennettCouchLamp',
    ASH_CAN = 'ashCan',
    GUITAR = 'guitar',
    BASS_CASE_OPEN = 'bassCaseOpen',
    DRUMKIT = 'drumKit',
    GUITAR_CASE_UPRIGHT = 'guitarCaseUpright',
    BASS_CASE_UPRIGHT = 'bassCaseUpright',
    CAVEMAN_BONES = 'cavemanBones',
    PUSH_BROOM = 'pushBroom',
    STEPLADDER = 'stepladder',
    MANNEQUIN = 'mannequin',
    CONVEYOR_BELT = 'conveyorBelt',
    GLASS_CART = 'glassCart',
    TRAY_CART = 'trayCart',
    GLASS_RACK = 'glassRack',
    DISH_PILE = 'dishPile',
    NUDE_DRAWINGS = 'nudeDrawings',
    VASELINE = 'vaseline',
    LIZ_PHONE = 'lizPhone',
    LIZ_PHONE_BASE = 'lizPhoneBase',
    LIZ_PHONE_REFLECTION = 'lizPhoneReflection',
    LIZ_PHONE_BASE_REFLECTION = 'lizPhoneBaseReflection',
    GRAVESTONE = 'gravestone',
    EVIAN_BOTTLES = 'evianBottles',
    STAGE_MIC_SIDE = 'stageMicSide',
    KICK_DRUM = 'kickDrum',
    GUITAR_CASE_OPEN = 'guitarCaseOpen',
    BASS_CASE_SIDE = 'bassCaseSide',
    DRUMS_STACKED = 'drumsStacked',
    RECORDING_CONSOLE = 'recordingConsole',
    RECORDING_MIC = 'recordingMic',
    RECORDING_BEERS = 'recordingBeers',
    STAGE_MIC_FAR = 'stageMicFar',
    BURGER_WRAPPER = 'burgerWrapper',
    HOSPITAL_RECORD_PLAYER = 'hospitalRecordPlayer',

    ARRANGEMENT_PUSH_BROOM_BACKSTAGE = 'arrangementPushBroomBackstage',
    ARRANGEMENT_PUSH_BROOM_TUNNEL = 'arrangementPushBroomTunnel',
    ARRANGEMENT_DRUMS_STACKED_BASEMENT = 'arrangementDrumsStackedBasement',
    ARRANGEMENT_DRUMS_STACKED_CLUB = 'arrangementDrumsStackedClub'

export {
    PLAYGROUND_BALL,
    RECORD_PLAYER_STOOL,
    SHOPPING_CART,
    CHRISTOPHER_LETTERS,
    BACKPACK_BENNETT,
    BACKPACK_SASHA,
    FRIDGE_DRAWINGS,
    BENNETT_LETTERS,
    CAPTAIN_BED_LAMP,
    THROWN_FRUIT,
    BENNETT_RECORD_PLAYER,
    BENNETT_COUCH_LAMP,
    ASH_CAN,
    GUITAR,
    BASS_CASE_OPEN,
    DRUMKIT,
    GUITAR_CASE_UPRIGHT,
    BASS_CASE_UPRIGHT,
    CAVEMAN_BONES,
    PUSH_BROOM,
    STEPLADDER,
    MANNEQUIN,
    CONVEYOR_BELT,
    GLASS_CART,
    TRAY_CART,
    GLASS_RACK,
    DISH_PILE,
    NUDE_DRAWINGS,
    VASELINE,
    LIZ_PHONE,
    LIZ_PHONE_BASE,
    LIZ_PHONE_REFLECTION,
    LIZ_PHONE_BASE_REFLECTION,
    GRAVESTONE,
    EVIAN_BOTTLES,
    STAGE_MIC_SIDE,
    KICK_DRUM,
    GUITAR_CASE_OPEN,
    BASS_CASE_SIDE,
    DRUMS_STACKED,
    RECORDING_CONSOLE,
    RECORDING_MIC,
    RECORDING_BEERS,
    STAGE_MIC_FAR,
    BURGER_WRAPPER,
    HOSPITAL_RECORD_PLAYER,

    ARRANGEMENT_PUSH_BROOM_BACKSTAGE,
    ARRANGEMENT_PUSH_BROOM_TUNNEL,
    ARRANGEMENT_DRUMS_STACKED_BASEMENT,
    ARRANGEMENT_DRUMS_STACKED_CLUB
}
