const
    NOHO_HOUSE_LEFT = 'nohoHouseLeft',
    NOHO_HOUSE_RIGHT = 'nohoHouseRight',
    NOHO_SCHOOLHOUSE = 'nohoSchoolhouse',
    NURSE_OFFICE_BUBBLE = 'nurseOfficeBubble',
    FAMILY_HOUSE = 'familyHouse',
    CAVE_SHADOWS = 'caveShadows',
    TAIWAN_MOUNTAINS_BRIDGED = 'taiwanMountainsBridged',
    TAIWAN_MOUNTAINS_NEAR = 'taiwanMountainsNear',
    TAIWAN_CLOUDS = 'taiwanClouds',
    TOGETHER_SKETCHBOOK = 'togetherSketchbook',
    VAN_NUYS_SCHOOLHOUSE = 'vanNuysSchoolhouse',
    APART_SKETCHBOOK = 'apartSketchbook',
    SHORE_BACK = 'shoreBack',
    OCEAN_DEPTHS_BACK = 'oceanDepthsBack',
    OCEAN_BOTTOM_FAR = 'oceanBottomFar',
    DOGS_SKETCHBOOK = 'dogsSketchbook',
    ESCAPE_POD_SKETCHBOOK = 'escapePodSketchbook',
    ST_JOSEPHS_ANNEX = 'stJosephsAnnex',
    ST_JOSEPHS_CHURCH = 'stJosephsChurch',
    CAMPANILE = 'campanile',
    CINEMA_THOUGHTS = 'cinemaThoughts',
    MUSEUM_DISPLAY = 'museumDisplay',
    ROYCE_HALL = 'royceHall',
    PHARMACY_AISLE = 'pharmacyAisle',
    STEAM_PIPES = 'steamPipes',
    CEMETERY_HILLS_NEAR = 'cemeteryHillsNear',
    TARPIT_THOUGHT = 'tarpitThought',
    SIBLING_THOUGHT = 'siblingThought',
    OAKLAND_HOUSE_LEFT = 'oaklandHouseLeft',
    OAKLAND_HOUSE_RIGHT = 'oaklandHouseRight',
    RESIDENTIAL_LEFT = 'residentialLeft',
    RESIDENTIAL_RIGHT = 'residentialRight',
    COMMERCIAL_LEFT = 'commercialLeft',
    COMMERCIAL_RIGHT = 'commercialRight',
    PUBLIC_LEFT = 'publicLeft',
    PUBLIC_RIGHT = 'publicRight',
    ROAD_PAST = 'roadPast',
    ROAD_PRESENT = 'roadPresent',
    ROAD_FUTURE = 'roadFuture',
    EL_CERRITO_ROAD = 'elCerritoRoad',
    PHONE_BUBBLE = 'phoneBubble',
    HOSPITAL_THOUGHT = 'hospitalThought',
    TENNIS_THOUGHT = 'tennisThought',
    CLIFF_GRAVES = 'cliffGraves'

export {
    NOHO_HOUSE_LEFT,
    NOHO_HOUSE_RIGHT,
    NOHO_SCHOOLHOUSE,
    NURSE_OFFICE_BUBBLE,
    FAMILY_HOUSE,
    CAVE_SHADOWS,
    TAIWAN_MOUNTAINS_BRIDGED,
    TAIWAN_MOUNTAINS_NEAR,
    TAIWAN_CLOUDS,
    TOGETHER_SKETCHBOOK,
    VAN_NUYS_SCHOOLHOUSE,
    APART_SKETCHBOOK,
    SHORE_BACK,
    OCEAN_DEPTHS_BACK,
    OCEAN_BOTTOM_FAR,
    DOGS_SKETCHBOOK,
    ESCAPE_POD_SKETCHBOOK,
    ST_JOSEPHS_ANNEX,
    ST_JOSEPHS_CHURCH,
    CAMPANILE,
    CINEMA_THOUGHTS,
    MUSEUM_DISPLAY,
    ROYCE_HALL,
    PHARMACY_AISLE,
    STEAM_PIPES,
    CEMETERY_HILLS_NEAR,
    TARPIT_THOUGHT,
    SIBLING_THOUGHT,
    OAKLAND_HOUSE_LEFT,
    OAKLAND_HOUSE_RIGHT,
    RESIDENTIAL_LEFT,
    RESIDENTIAL_RIGHT,
    COMMERCIAL_LEFT,
    COMMERCIAL_RIGHT,
    PUBLIC_LEFT,
    PUBLIC_RIGHT,
    ROAD_PAST,
    ROAD_PRESENT,
    ROAD_FUTURE,
    EL_CERRITO_ROAD,
    PHONE_BUBBLE,
    HOSPITAL_THOUGHT,
    TENNIS_THOUGHT,
    CLIFF_GRAVES
}
