// Keep flat instances in this file.

const
    NOHO_HOUSES_BACKDROP = 'nohoHousesBackdrop',
    NOHO_HOUSE_LEFT = 'nohoHouseLeft',
    NOHO_HOUSE_RIGHT = 'nohoHouseRight',
    NOHO_SCHOOL_BACKDROP = 'nohoSchoolBackdrop',
    NOHO_SCHOOLHOUSE = 'nohoSchoolhouse',
    NURSE_OFFICE_BUBBLE = 'nurseOfficeBubble',
    VALLEY_BACKDROP = 'valleyBackdrop',
    BEDROOM_BACKDROP = 'bedroomBackdrop',
    BEDROOM_SIREN_BACKDROP = 'bedroomSirenBackdrop',
    BEDROOM_BUS_BACKDROP = 'bedroomBusBackdrop',
    CAPTAIN_BED_DRAWERS = 'captainBedDrawers',
    DOGS_SKETCHBOOK = 'dogsSketchbook',
    SPACE_STATION_SKETCHBOOK = 'spaceStationSketchbook',
    FAMILY_HOUSE = 'familyHouse',
    CAVE_SHADOWS = 'caveShadows',
    STALACTITES = 'stalactites',
    TAIWAN_MOUNTAINS_FAR = 'taiwanMountainsFar',
    TAIWAN_MOUNTAINS_BRIDGED = 'taiwanMountainsBridged',
    TAIWAN_MOUNTAINS_NEAR = 'taiwanMountainsNear',
    TAIWAN_CLOUDS = 'taiwanClouds',
    SCHOOLBUS_STREET_THOUGHT = 'schoolbusStreetThought',
    VAN_NUYS_SCHOOL_THOUGHT = 'vanNuysSchoolThought',
    VAN_NUYS_SCHOOLHOUSE = 'vanNuysSchoolhouse',
    TAIWAN_GATE = 'taiwanGate',
    TAIWAN_STREETS_BACKDROP = 'taiwanStreetsBackdrop',
    SHORE_BACKDROP = 'shoreBackdrop',
    SHORE_FRONT = 'shoreFront',
    SHORE_BACK = 'shoreBack',
    OCEAN_DEPTHS_FRONT = 'oceanDepthsFront',
    OCEAN_DEPTHS_BACK = 'oceanDepthsBack',
    OCEAN_WAVES = 'oceanWaves',
    OCEAN_BOTTOM_FAR = 'oceanBottomFar',
    OCEAN_BOTTOM_NEAR = 'oceanBottomNear',
    VAN_NUYS_SCHOOL_BACKDROP = 'vanNuysSchoolBackdrop'

export {
    NOHO_HOUSES_BACKDROP,
    NOHO_HOUSE_LEFT,
    NOHO_HOUSE_RIGHT,
    NOHO_SCHOOL_BACKDROP,
    NOHO_SCHOOLHOUSE,
    NURSE_OFFICE_BUBBLE,
    VALLEY_BACKDROP,
    BEDROOM_BACKDROP,
    BEDROOM_SIREN_BACKDROP,
    BEDROOM_BUS_BACKDROP,
    CAPTAIN_BED_DRAWERS,
    DOGS_SKETCHBOOK,
    SPACE_STATION_SKETCHBOOK,
    FAMILY_HOUSE,
    CAVE_SHADOWS,
    STALACTITES,
    TAIWAN_MOUNTAINS_FAR,
    TAIWAN_MOUNTAINS_BRIDGED,
    TAIWAN_MOUNTAINS_NEAR,
    TAIWAN_CLOUDS,
    SCHOOLBUS_STREET_THOUGHT,
    VAN_NUYS_SCHOOL_THOUGHT,
    VAN_NUYS_SCHOOLHOUSE,
    TAIWAN_GATE,
    TAIWAN_STREETS_BACKDROP,
    SHORE_BACKDROP,
    SHORE_FRONT,
    SHORE_BACK,
    OCEAN_DEPTHS_FRONT,
    OCEAN_DEPTHS_BACK,
    OCEAN_WAVES,
    OCEAN_BOTTOM_FAR,
    OCEAN_BOTTOM_NEAR,
    VAN_NUYS_SCHOOL_BACKDROP
}
