// Keep flat instances in this file.

const
    NOHO_HOUSES_BACKDROP = 'nohoHousesBackdrop',
    NOHO_HOUSE_LEFT = 'nohoHouseLeft',
    NOHO_HOUSE_RIGHT = 'nohoHouseRight',
    NOHO_SCHOOL_BACKDROP = 'nohoSchoolBackdrop',
    NOHO_SCHOOLHOUSE = 'nohoSchoolhouse',
    NURSE_OFFICE_BUBBLE = 'nurseOfficeBubble',
    VALLEY_BACKDROP = 'valleyBackdrop',
    BEDROOM_BACKDROP = 'bedroomBackdrop',
    BEDROOM_SIREN_BACKDROP = 'bedroomSirenBackdrop',
    CAPTAIN_BED_DRAWERS = 'captainBedDrawers',
    FAMILY_HOUSE = 'familyHouse',
    CAVE_SHADOWS = 'caveShadows',
    STALACTITES = 'stalactites',
    TAIWAN_MOUNTAINS_FAR = 'taiwanMountainsFar',
    TAIWAN_MOUNTAINS_BRIDGED = 'taiwanMountainsBridged',
    TAIWAN_MOUNTAINS_NEAR = 'taiwanMountainsNear',
    TAIWAN_CLOUDS = 'taiwanClouds',
    TOGETHER_SKETCHBOOK = 'togetherSketchbook',
    SCHOOLBUS_STREET_THOUGHT = 'schoolbusStreetThought',
    VAN_NUYS_SCHOOL_THOUGHT = 'vanNuysSchoolThought',
    VAN_NUYS_SCHOOLHOUSE = 'vanNuysSchoolhouse',
    APART_SKETCHBOOK = 'apartSketchbook',
    TAIWAN_GATE = 'taiwanGate',
    TAIWAN_STREETS_BACKDROP = 'taiwanStreetsBackdrop',
    SHORE_BACKDROP = 'shoreBackdrop',
    SHORE_FRONT = 'shoreFront',
    SHORE_BACK = 'shoreBack',
    OCEAN_DEPTHS_FRONT = 'oceanDepthsFront',
    OCEAN_DEPTHS_BACK = 'oceanDepthsBack',
    OCEAN_WAVES = 'oceanWaves',
    OCEAN_BOTTOM_FAR = 'oceanBottomFar',
    OCEAN_BOTTOM_NEAR = 'oceanBottomNear',
    DOGS_SKETCHBOOK = 'dogsSketchbook',
    BEDROOM_BUS_BACKDROP = 'bedroomBusBackdrop',
    ESCAPE_POD_SKETCHBOOK = 'escapePodSketchbook',
    VAN_NUYS_SCHOOL_BACKDROP = 'vanNuysSchoolBackdrop',
    BENNETT_COUCH_THOUGHT = 'bennettCouchThought',
    WEST_BERKELEY_BACKDROP = 'westBerkeleyBackdrop',
    ST_JOSEPHS_CHURCH = 'stJosephsChurch',
    UC_BERKELEY_BACKDROP = 'ucBerkeleyBackdrop',
    CAMPANILE = 'campanile',
    BAY_AREA_BACKDROP = 'bayAreaBackdrop',
    CINEMA_THOUGHTS = 'cinemaThoughts',
    MUSEUM_DISPLAY = 'museumDisplay',
    GO_KART_THOUGHT = 'goKartThought',
    UCLA_BACKDROP = 'uclaBackdrop',
    ROYCE_HALL = 'royceHall',
    PHARMACY_THOUGHT = 'pharmacyThought',
    PHARMACY_AISLE = 'pharmacyAisle',
    STEAM_PIPES = 'steamPipes',
    CEMETERY_HILLS_NEAR = 'cemeteryHillsNear',
    CEMETERY_HILLS_FAR = 'cemeteryHillsFar',
    LOS_ANGELES_BACKDROP = 'losAngelesBackdrop',
    TARPIT_THOUGHT = 'tarpitThought',
    SIBLING_THOUGHT = 'siblingThought'

export {
    NOHO_HOUSES_BACKDROP,
    NOHO_HOUSE_LEFT,
    NOHO_HOUSE_RIGHT,
    NOHO_SCHOOL_BACKDROP,
    NOHO_SCHOOLHOUSE,
    NURSE_OFFICE_BUBBLE,
    VALLEY_BACKDROP,
    BEDROOM_BACKDROP,
    BEDROOM_SIREN_BACKDROP,
    CAPTAIN_BED_DRAWERS,
    FAMILY_HOUSE,
    CAVE_SHADOWS,
    STALACTITES,
    TAIWAN_MOUNTAINS_FAR,
    TAIWAN_MOUNTAINS_BRIDGED,
    TAIWAN_MOUNTAINS_NEAR,
    TAIWAN_CLOUDS,
    TOGETHER_SKETCHBOOK,
    SCHOOLBUS_STREET_THOUGHT,
    VAN_NUYS_SCHOOL_THOUGHT,
    VAN_NUYS_SCHOOLHOUSE,
    APART_SKETCHBOOK,
    TAIWAN_GATE,
    TAIWAN_STREETS_BACKDROP,
    SHORE_BACKDROP,
    SHORE_FRONT,
    SHORE_BACK,
    OCEAN_DEPTHS_FRONT,
    OCEAN_DEPTHS_BACK,
    OCEAN_WAVES,
    OCEAN_BOTTOM_FAR,
    OCEAN_BOTTOM_NEAR,
    DOGS_SKETCHBOOK,
    BEDROOM_BUS_BACKDROP,
    ESCAPE_POD_SKETCHBOOK,
    VAN_NUYS_SCHOOL_BACKDROP,
    BENNETT_COUCH_THOUGHT,
    WEST_BERKELEY_BACKDROP,
    ST_JOSEPHS_CHURCH,
    UC_BERKELEY_BACKDROP,
    CAMPANILE,
    BAY_AREA_BACKDROP,
    CINEMA_THOUGHTS,
    MUSEUM_DISPLAY,
    GO_KART_THOUGHT,
    UCLA_BACKDROP,
    ROYCE_HALL,
    PHARMACY_THOUGHT,
    PHARMACY_AISLE,
    STEAM_PIPES,
    CEMETERY_HILLS_NEAR,
    CEMETERY_HILLS_FAR,
    LOS_ANGELES_BACKDROP,
    TARPIT_THOUGHT,
    SIBLING_THOUGHT
}
