// Keep furniture instances in this file.

const
    PORCH_DOOR = 'porchDoor',
    BEDROOM_BLINDS = 'bedroomBlinds',
    BEDROOM_BLINDS_OPEN = 'bedroomBlindsOpen',
    CAPTAIN_BED_MATTRESS = 'captainBedMattress',
    SCHOOLBUS_SEAT_FRONT = 'schoolbusSeatFront',
    SCHOOLBUS_SEAT_BACK = 'schoolbusSeatBack',
    SLEEPING_MAT = 'sleepingMat',
    STAIRWELL_RAILING = 'stairwellRailing',
    IRON_GATE = 'ironGate',
    BUOY_FLOAT = 'buoy',
    PRINCIPAL_DOOR = 'principalDoor',
    BENNETT_BLINDS = 'bennettBlinds',
    BENNETT_DOOR_OUTSIDE = 'bennettDoorOutside',
    BENNETT_GATE_SIDE = 'bennettGateSide',
    BENNETT_CUSHIONS = 'bennettCushions',
    BANCROFT_DOOR = 'bancroftDoor',
    BASEMENT_DOOR = 'basementDoor',
    BASEMENT_DOOR_OPEN = 'basementDoorOpen',
    CINEMA_DOORS = 'cinemaDoors',
    LIZ_BLINDS = 'lizBlinds',
    LIZ_GATE_OUTSIDE = 'lizGateOutside',
    GO_KART_INTERIOR_LEFT = 'goKartInteriorLeft',
    GO_KART_INTERIOR_RIGHT = 'goKartInteriorRight',
    LIZ_GATE_OUTSIDE_OPEN = 'lizGateOutsideOpen',
    DISHROOM_DOOR = 'dishroomDoor',
    BENNETT_GATE_FRONT = 'bennettGateFront',
    BENNETT_GATE_SIDE_OPEN = 'bennettGateSideOpen',
    BENNETT_DOOR_INSIDE = 'bennettDoorInside',
    BENNETT_DOOR_INSIDE_OPEN = 'bennettDoorInsideOpen',
    BENNETT_MATTRESS = 'bennettMattress',
    BENNETT_PILLOWS = 'bennettPillows',
    ARMCHAIR_LEFT = 'armchairLeft',
    ARMCHAIR_RIGHT = 'armchairRight',
    WAITING_ROOM_DOOR = 'waitingRoomDoor',
    WAITING_ROOM_DOOR_OPEN = 'waitingRoomDoorOpen',
    LIZ_MATTRESS = 'lizMattress',
    LIZ_PILLOWS = 'lizPillows',
    LIZ_MATTRESS_REFLECTION = 'lizMattressReflection',
    LIZ_PILLOWS_REFLECTION = 'lizPillowsReflection',
    STATION_WAGON_SEAT_FRONT = 'stationWagonSeatFront',
    STATION_WAGON_SEAT_BACK = 'stationWagonSeatBack',
    ATTIC_CUSHIONS = 'atticCushions',
    CLUB_DOOR = 'clubDoor'

export {
    PORCH_DOOR,
    BEDROOM_BLINDS,
    BEDROOM_BLINDS_OPEN,
    CAPTAIN_BED_MATTRESS,
    SCHOOLBUS_SEAT_FRONT,
    SCHOOLBUS_SEAT_BACK,
    SLEEPING_MAT,
    STAIRWELL_RAILING,
    IRON_GATE,
    BUOY_FLOAT,
    PRINCIPAL_DOOR,
    BENNETT_BLINDS,
    BENNETT_DOOR_OUTSIDE,
    BENNETT_GATE_SIDE,
    BENNETT_CUSHIONS,
    BANCROFT_DOOR,
    BASEMENT_DOOR,
    BASEMENT_DOOR_OPEN,
    CINEMA_DOORS,
    LIZ_BLINDS,
    LIZ_GATE_OUTSIDE,
    GO_KART_INTERIOR_LEFT,
    GO_KART_INTERIOR_RIGHT,
    LIZ_GATE_OUTSIDE_OPEN,
    DISHROOM_DOOR,
    BENNETT_GATE_FRONT,
    BENNETT_GATE_SIDE_OPEN,
    BENNETT_DOOR_INSIDE,
    BENNETT_DOOR_INSIDE_OPEN,
    BENNETT_MATTRESS,
    BENNETT_PILLOWS,
    ARMCHAIR_LEFT,
    ARMCHAIR_RIGHT,
    WAITING_ROOM_DOOR,
    WAITING_ROOM_DOOR_OPEN,
    LIZ_MATTRESS,
    LIZ_PILLOWS,
    LIZ_MATTRESS_REFLECTION,
    LIZ_PILLOWS_REFLECTION,
    STATION_WAGON_SEAT_FRONT,
    STATION_WAGON_SEAT_BACK,
    ATTIC_CUSHIONS,
    CLUB_DOOR
}
