const
    CAPTAIN_BED_MATTRESS = 'captainBedMattress',
    SCHOOLBUS_SEAT_FRONT = 'schoolbusSeatFront',
    SCHOOLBUS_SEAT_REAR = 'schoolbusSeatBack',
    STAIRWELL_RAILING = 'stairwellRailing',
    BUOY_FLOAT = 'buoy',
    BENNETT_CUSHIONS = 'bennettCushions',
    GO_KART_SEAT_LEFT = 'goKartSeatLeft',
    GO_KART_SEAT_RIGHT = 'goKartSeatRight',
    GO_KART_DASHBOARD_LEFT = 'goKartDashboardLeft',
    GO_KART_DASHBOARD_RIGHT = 'goKartDashboardRight',
    BENNETT_MATTRESS = 'bennettMattress',
    BENNETT_PILLOWS = 'bennettPillows',
    ARMCHAIR_LEFT = 'armchairLeft',
    ARMCHAIR_RIGHT = 'armchairRight',
    LIZ_MATTRESS = 'lizMattress',
    LIZ_PILLOWS = 'lizPillows',
    LIZ_MATTRESS_REFLECTION = 'lizMattressReflection',
    LIZ_PILLOWS_REFLECTION = 'lizPillowsReflection',
    SATURN_SEAT_FRONT = 'saturnSeatFront',
    SATURN_SEAT_REAR = 'saturnSeatRear',
    SATURN_DASHBOARD = 'saturnDashboard',
    ATTIC_CUSHIONS = 'atticCushions',
    LIZ_CUSHIONS = 'lizCushions',
    MIRIAM_CUSHIONS = 'miriamCushions',
    REATTA_SEAT = 'reattaSeat',
    REATTA_SEAT_LOWERED = 'reattaSeatLowered',
    REATTA_DASHBOARD = 'reattaDashboard',
    HOSPITAL_MATTRESS = 'hospitalMattress'

export {
    CAPTAIN_BED_MATTRESS,
    SCHOOLBUS_SEAT_FRONT,
    SCHOOLBUS_SEAT_REAR,
    STAIRWELL_RAILING,
    BUOY_FLOAT,
    BENNETT_CUSHIONS,
    GO_KART_SEAT_LEFT,
    GO_KART_SEAT_RIGHT,
    GO_KART_DASHBOARD_LEFT,
    GO_KART_DASHBOARD_RIGHT,
    BENNETT_MATTRESS,
    BENNETT_PILLOWS,
    ARMCHAIR_LEFT,
    ARMCHAIR_RIGHT,
    LIZ_MATTRESS,
    LIZ_PILLOWS,
    LIZ_MATTRESS_REFLECTION,
    LIZ_PILLOWS_REFLECTION,
    SATURN_SEAT_FRONT,
    SATURN_SEAT_REAR,
    SATURN_DASHBOARD,
    ATTIC_CUSHIONS,
    LIZ_CUSHIONS,
    MIRIAM_CUSHIONS,
    REATTA_SEAT,
    REATTA_SEAT_LOWERED,
    REATTA_DASHBOARD,
    HOSPITAL_MATTRESS
}
