const

// Other.
DEFAULT_HSLA = 'default',

STAGE_FLOOR_HSLA = 'stageFloor',
STAGE_PLATFORM_HSLA = 'stagePlatform',

STREET_HSLA = 'street',
SIDEWALK_HSLA = 'sidewalk',
GROUND_HSLA = 'ground',
LAWN_HSLA = 'lawn',

CEILING_HSLA = 'ceiling',
FLOOR_HSLA = 'floor',
WALL_HSLA = 'wall',

SEAT_HSLA = 'seat',

HSLA_KEYS = [
    DEFAULT_HSLA,
    STAGE_FLOOR_HSLA,
    STAGE_PLATFORM_HSLA,
    STREET_HSLA,
    SIDEWALK_HSLA,
    GROUND_HSLA,
    LAWN_HSLA,
    CEILING_HSLA,
    FLOOR_HSLA,
    WALL_HSLA,
    SEAT_HSLA
]

export {
    HSLA_KEYS,

    DEFAULT_HSLA,
    STAGE_FLOOR_HSLA,
    STAGE_PLATFORM_HSLA,
    STREET_HSLA,
    SIDEWALK_HSLA,
    GROUND_HSLA,
    LAWN_HSLA,
    CEILING_HSLA,
    FLOOR_HSLA,
    WALL_HSLA,
    SEAT_HSLA
}
