export const BOOK__SHARED = 'book'
export const LETTER__SHARED = 'letter'
export const MAGAZINE__SHARED = 'magazine'
export const NEWSPAPER__SHARED = 'newspaper'
export const SKETCHBOOK__SHARED = 'sketchbook'
