export const BUDDHA_SHRINE__SHARED = 'buddhaShrine'
export const TAIWAN_BUOY__SHARED = 'taiwanBuoy'
export const TAIWAN_MOUNTAIN__SHARED = 'taiwanMountain'
export const TAIWAN_PILLOW__SHARED = 'taiwanPillow'
export const TAIWAN_RICKSHAW__SHARED = 'taiwanRickshaw'
