export const BENNETT_PILLOW = 'bennettPillow'
export const CAPTAIN_BED_PILLOW = 'captainBedPillow'
export const LIZ_PILLOWS = 'lizPillows'
export const LIZ_PILLOWS_REFLECTION = 'lizPillowsReflection'
export const LIZ_PILLOWS_PILE = 'lizPillowsPile'
export const LIZ_PILLOWS_PILE_REFLECTION = 'lizPillowsPileReflection'
