export const ACOUSTIC_GUITAR__SHARED = 'acousticGuitar__shared'
export const BANJO__SHARED = 'banjo__shared'
export const BASS__SHARED = 'bass__shared'
export const BASS_CASE__SHARED = 'bassCase__shared'
export const ELECTRIC_GUITAR__SHARED = 'electricGuitar__shared'
export const GUITAR_CASE__SHARED = 'guitarCase__shared'
export const MICROPHONE__SHARED = 'microphone__shared'
export const VIOLIN__SHARED = 'violin__shared'
