import {
    CUTOUTS,
    FIXTURES,
    FLATS
} from 'constants/scene'

import {
    YOUNG_BENNETT,
    PRETEEN_BENNETT,
    BENNETT,
    OLD_BENNETT,
    ANITA,
    ESTHER,
    WILLY,
    MOTHER,
    FATHER,
    CHRISTOPHER,
    SASHA,
    BRAD,
    ANDREW,
    CATHERINE,
    MARA,
    JACOB,
    ANA,
    HOWIE,
    TOMER,
    LIZ,
    KHARI,
    MIRIAM,
    TRISTAN,
    NESTOR,
    AMY,
    STEPHANIE,
    WADE,
    BENNETT_REFLECTION,
    LIZ_REFLECTION,
    KHARI_REFLECTION
} from 'scene/actorKeys'

import ARRANGEMENTS_YOUNG_BENNETT from './youngBennett'
import ARRANGEMENTS_PRETEEN_BENNETT from './preteenBennett'
import {
    ARRANGEMENTS_BENNETT,
    ARRANGEMENTS_BENNETT_REFLECTION
} from './bennett'
import ARRANGEMENTS_OLD_BENNETT from './oldBennett'
import ARRANGEMENTS_ANITA from './anita'
import ARRANGEMENTS_ESTHER from './esther'
import ARRANGEMENTS_WILLY from './willy'
import ARRANGEMENTS_MOTHER from './mother'
import ARRANGEMENTS_FATHER from './father'
import ARRANGEMENTS_CHRISTOPHER from './christopher'
import ARRANGEMENTS_SASHA from './sasha'
import ARRANGEMENTS_BRAD from './brad'
import ARRANGEMENTS_ANDREW from './andrew'
import ARRANGEMENTS_CATHERINE from './catherine'
import ARRANGEMENTS_MARA from './mara'
import ARRANGEMENTS_JACOB from './jacob'
import ARRANGEMENTS_ANA from './ana'
import ARRANGEMENTS_HOWIE from './howie'
import ARRANGEMENTS_TOMER from './tomer'
import {
    ARRANGEMENTS_LIZ,
    ARRANGEMENTS_LIZ_REFLECTION
} from './liz'
import {
    ARRANGEMENTS_KHARI,
    ARRANGEMENTS_KHARI_REFLECTION
} from './khari'
import ARRANGEMENTS_MIRIAM from './miriam'
import ARRANGEMENTS_TRISTAN from './tristan'
import ARRANGEMENTS_NESTOR from './nestor'
import ARRANGEMENTS_AMY from './amy'
import ARRANGEMENTS_STEPHANIE from './stephanie'
import ARRANGEMENTS_WADE from './wade'

import ARRANGEMENTS_CUTOUTS from './cutouts'
import ARRANGEMENTS_FIXTURES from './fixtures'
import ARRANGEMENTS_FLATS from './flats'

const ALL_ARRANGEMENTS = {
    [YOUNG_BENNETT]: ARRANGEMENTS_YOUNG_BENNETT,
    [PRETEEN_BENNETT]: ARRANGEMENTS_PRETEEN_BENNETT,
    [BENNETT]: ARRANGEMENTS_BENNETT,
    [OLD_BENNETT]: ARRANGEMENTS_OLD_BENNETT,
    [ANITA]: ARRANGEMENTS_ANITA,
    [ESTHER]: ARRANGEMENTS_ESTHER,
    [WILLY]: ARRANGEMENTS_WILLY,
    [MOTHER]: ARRANGEMENTS_MOTHER,
    [FATHER]: ARRANGEMENTS_FATHER,
    [CHRISTOPHER]: ARRANGEMENTS_CHRISTOPHER,
    [SASHA]: ARRANGEMENTS_SASHA,
    [BRAD]: ARRANGEMENTS_BRAD,
    [ANDREW]: ARRANGEMENTS_ANDREW,
    [CATHERINE]: ARRANGEMENTS_CATHERINE,
    [MARA]: ARRANGEMENTS_MARA,
    [JACOB]: ARRANGEMENTS_JACOB,
    [ANA]: ARRANGEMENTS_ANA,
    [HOWIE]: ARRANGEMENTS_HOWIE,
    [TOMER]: ARRANGEMENTS_TOMER,
    [LIZ]: ARRANGEMENTS_LIZ,
    [KHARI]: ARRANGEMENTS_KHARI,
    [MIRIAM]: ARRANGEMENTS_MIRIAM,
    [TRISTAN]: ARRANGEMENTS_TRISTAN,
    [NESTOR]: ARRANGEMENTS_NESTOR,
    [AMY]: ARRANGEMENTS_AMY,
    [STEPHANIE]: ARRANGEMENTS_STEPHANIE,
    [WADE]: ARRANGEMENTS_WADE,
    [BENNETT_REFLECTION]: ARRANGEMENTS_BENNETT_REFLECTION,
    [LIZ_REFLECTION]: ARRANGEMENTS_LIZ_REFLECTION,
    [KHARI_REFLECTION]: ARRANGEMENTS_KHARI_REFLECTION,

    [CUTOUTS]: ARRANGEMENTS_CUTOUTS,
    [FIXTURES]: ARRANGEMENTS_FIXTURES,
    [FLATS]: ARRANGEMENTS_FLATS
}

export default ALL_ARRANGEMENTS
