import {
    BENNETT_PILLOW,
    CAPTAIN_BED_PILLOW,
    LIZ_PILLOWS_PILE,
    LIZ_PILLOWS_PILE_REFLECTION
} from '../../../../constants/scene/things/furnitures'

import {
    BENNETT_LINENS__SHARED,
    LIZ_LINENS__SHARED,
    PRETEEN_LINENS__SHARED
} from '../../../sharedStyles/furniture'

export default {
    [BENNETT_PILLOW]: BENNETT_LINENS__SHARED,
    [CAPTAIN_BED_PILLOW]: PRETEEN_LINENS__SHARED,
    [LIZ_PILLOWS_PILE]: LIZ_LINENS__SHARED,
    [LIZ_PILLOWS_PILE_REFLECTION]: LIZ_LINENS__SHARED
}
