import { ACTOR } from 'constants/scene'
import {
    OLD_BENNETT,
    BENNETT,
    LIZ,
    CHRISTOPHER,
    ANITA,
    YOUNG_BENNETT,
    ESTHER,
    WILLY,
    MOTHER,
    FATHER,
    SASHA,
    PRETEEN_BENNETT,
    BRAD,
    ANDREW,
    CATHERINE,
    MARA,
    JACOB,
    ANA,
    HOWIE,
    TOMER,
    KHARI,
    MIRIAM,
    TRISTAN,
    NESTOR,
    AMY,
    STEPHANIE,
    WADE
} from 'constants/scene/actors'
import { EPILOGUE } from 'constants/scene/actors/instances/songs'

export default [
    {
        presences: {
            [ACTOR]: {
                [OLD_BENNETT]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'4"`,
                    instance: EPILOGUE
                },
                [BENNETT]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'4"`,
                    instance: EPILOGUE
                },
                [LIZ]: {
                    todo: true,
                    faceRevision: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'9"`,
                    instance: EPILOGUE
                },
                [CHRISTOPHER]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `3'5"`,
                    instance: EPILOGUE
                },
                [ANITA]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `3'9"`,
                    instance: EPILOGUE
                },
                [YOUNG_BENNETT]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `3'6"`,
                    instance: EPILOGUE
                },
                [ESTHER]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `3'10"`,
                    instance: EPILOGUE
                },
                [WILLY]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'3"`,
                    instance: EPILOGUE
                },
                [MOTHER]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'0"`,
                    instance: EPILOGUE
                },
                [FATHER]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'4"`,
                    instance: EPILOGUE
                },
                [HOWIE]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `6'0"`,
                    instance: EPILOGUE
                },
                [TOMER]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'6"`,
                    instance: EPILOGUE
                },
                [SASHA]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'1"`,
                    instance: EPILOGUE
                },
                [PRETEEN_BENNETT]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'1"`,
                    instance: EPILOGUE
                },
                [BRAD]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'6"`,
                    instance: EPILOGUE
                },
                [ANDREW]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'7"`,
                    instance: EPILOGUE
                },
                [TRISTAN]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'8"`,
                    instance: EPILOGUE
                },
                [CATHERINE]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `4'11"`,
                    instance: EPILOGUE
                },
                [WADE]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'10"`,
                    instance: EPILOGUE
                },
                [AMY]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'6"`,
                    instance: EPILOGUE
                },
                [STEPHANIE]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'4"`,
                    instance: EPILOGUE
                },
                [JACOB]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'11"`,
                    instance: EPILOGUE
                },
                [MARA]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'0"`,
                    instance: EPILOGUE
                },
                [ANA]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'8"`,
                    instance: EPILOGUE
                },
                [MIRIAM]: {
                    todo: true,
                    hair: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'1"`,
                    instance: EPILOGUE
                },
                [KHARI]: {
                    todo: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'9"`,
                    instance: EPILOGUE
                },
                [NESTOR]: {
                    todo: true,
                    faceRevision: true,
                    feet: true,
                    legs: true,
                    trunk: true,
                    hands: true,
                    head: true,
                    face: true,
                    composite: true,
                    realHeight: `5'7"`,
                    instance: EPILOGUE
                }
            }
        }
    }
]
