import {
    BREAKUP_DEJECTED,
    SOLICITING_OPINION,
    CATHOLIC_PENSIVE,
    CATHOLIC_IDEA,
    PIOUS,
    PONDERING,
    RUBIKS_CUBE,
    COUCH_READING,
    DISTRACTED,
    HOPELESSLY_CRUSHED,
    WONDERING_BABY,
    MERRILY_DERANGED,
    DISHROOM_READING,
    MOP_SOPPED,
    WAITING_ROOM_ASLEEP,
    SIDELONG_HESITANCE,
    REMOVING_SHOES,
    DROPPING_MEATS,
    CORD_SIDE,
    CORD_REAR,
    REMOVING_PANTS,
    INFIRM,
    DISPOSING_CONDOM,
    CAMPUS_ASHAMED,
    SHOW_ANNOYED,
    ALLEY,
    BROKEN_HEARTED,
    DEMONSTRATION
} from 'constants/scene/actors/bennett'

import {
    EATING,
    DATE_ENDING,
    MUSEUM,
    BACKSTAGE,
    GO_KARTS,
    DATE_ENDED,
    DISHROOM_LANCET,
    GATE_CODE,
    RUMPLED_LINENS,
    ABBEY_ROAD,
    WALGREENS,
    STEAM_TUNNEL,
    CEMETERY,
    STATION_WAGON,
    ATTIC,
    PERFORMING,
    FLIRTING,
    GREETING,
    LEAVING_CRUMBLED,
    PAST,
    FUTURE,
    EL_TORITO
} from 'constants/scene/actors/songs'

export default {
    [BREAKUP_DEJECTED]: null,
    [SOLICITING_OPINION]: null,
    [CATHOLIC_PENSIVE]: null,
    [CATHOLIC_IDEA]: null,
    [PIOUS]: null,
    [PONDERING]: null,
    [COUCH_READING]: null,
    [RUBIKS_CUBE]: null,
    [DISTRACTED]: null,
    [HOPELESSLY_CRUSHED]: null,
    [WONDERING_BABY]: null,
    [MERRILY_DERANGED]: null,
    [EATING]: null,
    [DATE_ENDING]: null,
    [MUSEUM]: null,
    [BACKSTAGE]: null,
    [GO_KARTS]: null,
    [DATE_ENDED]: null,
    [DISHROOM_READING]: null,
    [DISHROOM_LANCET]: null,
    [MOP_SOPPED]: null,
    [GATE_CODE]: null,
    [RUMPLED_LINENS]: null,
    [WAITING_ROOM_ASLEEP]: null,
    [ABBEY_ROAD]: null,
    [WALGREENS]: null,
    [STEAM_TUNNEL]: null,
    [CEMETERY]: null,
    [STATION_WAGON]: null,
    [ATTIC]: null,
    [PERFORMING]: null,
    [FLIRTING]: null,
    [SIDELONG_HESITANCE]: null,
    [REMOVING_SHOES]: null,
    [DROPPING_MEATS]: null,
    [GREETING]: null,
    [LEAVING_CRUMBLED]: null,
    [CORD_SIDE]: null,
    [CORD_REAR]: null,
    [PAST]: null,
    [FUTURE]: null,
    [REMOVING_PANTS]: null,
    [INFIRM]: null,
    [DISPOSING_CONDOM]: null,
    [CAMPUS_ASHAMED]: null,
    [SHOW_ANNOYED]: null,
    [ALLEY]: null,
    [BROKEN_HEARTED]: null,
    [DEMONSTRATION]: null,
    [EL_TORITO]: null
}
