import {
    PRETEEN_BENNETT,
    WILLY,
    CHRISTOPHER
} from '../../actorKeys'

import ARRANGEMENTS_PRETEEN_BENNETT from './actors/preteenBennett'
import ARRANGEMENTS_WILLY from './actors/willy'
import ARRANGEMENTS_CHRISTOPHER from './actors/christopher'

const ARRANGEMENTS_ACTORS = {
    [PRETEEN_BENNETT]: ARRANGEMENTS_PRETEEN_BENNETT,
    [WILLY]: ARRANGEMENTS_WILLY,
    [CHRISTOPHER]: ARRANGEMENTS_CHRISTOPHER
}

export default ARRANGEMENTS_ACTORS
