import {
    CHRISTOPHER_BENNETT,
    WILLY
} from '../../actorKeys'

import ARRANGEMENTS_CHRISTOPHER_BENNETT from './actors/christopherBennett'
import ARRANGEMENTS_WILLY from './actors/willy'

const ARRANGEMENTS_ACTORS = {
    [CHRISTOPHER_BENNETT]: ARRANGEMENTS_CHRISTOPHER_BENNETT,
    [WILLY]: ARRANGEMENTS_WILLY
}

export default ARRANGEMENTS_ACTORS
