import {
    BENNETT_STEPHANIE,
    AMY_NESTOR_TOMER
} from '../../actorKeys'

import ARRANGEMENTS_BENNETT_STEPHANIE from './actors/bennettStephanie'
import ARRANGEMENTS_AMY_NESTOR_TOMER from './actors/amyNestorTomer'

const ARRANGEMENTS_ACTORS = {
    [BENNETT_STEPHANIE]: ARRANGEMENTS_BENNETT_STEPHANIE,
    [AMY_NESTOR_TOMER]: ARRANGEMENTS_AMY_NESTOR_TOMER
}

export default ARRANGEMENTS_ACTORS
