import {
    BENNETT,
    AMY_NESTOR_TOMER,
    STEPHANIE
} from '../../actorKeys'

import ARRANGEMENTS_BENNETT from './actors/bennett'
import ARRANGEMENTS_AMY_NESTOR_TOMER from './actors/amyNestorTomer'
import ARRANGEMENTS_STEPHANIE from './actors/stephanie'

const ARRANGEMENTS_ACTORS = {
    [BENNETT]: ARRANGEMENTS_BENNETT,
    [AMY_NESTOR_TOMER]: ARRANGEMENTS_AMY_NESTOR_TOMER,
    [STEPHANIE]: ARRANGEMENTS_STEPHANIE
}

export default ARRANGEMENTS_ACTORS
