import {
    BEDROOM_BUS,
    BEDROOM_SIREN,
    BERKELEY_BUILDING_TALL,
    BERKELEY_BUILDING_WIDE,
    CAMPANILE,
    CEMETERY_HILLS_LEFT,
    CEMETERY_HILLS_RIGHT,
    CLIFF_GRAVES_FAR,
    CLIFF_GRAVES_NEAR,
    COMMERCIAL_CENTRE,
    COMMERCIAL_FAR_LEFT,
    COMMERCIAL_FAR_RIGHT,
    COMMERCIAL_MIDDLE_LEFT,
    COMMERCIAL_MIDDLE_RIGHT,
    COMMERCIAL_NEAR_LEFT,
    COMMERCIAL_NEAR_RIGHT,
    DRIVING_HOUSE_LEFT,
    DRIVING_HOUSE_RIGHT,
    EL_CERRITO_FAR,
    EL_CERRITO_NEAR,
    FAMILY_HOUSE,
    FERRIS_WHEEL,
    FOREBODING_TREES,
    GO_KART_TRACK,
    NOHO_HOUSE_LEFT,
    NOHO_HOUSE_RIGHT,
    OAKLAND_FLAG,
    OAKLAND_HOUSE_LEFT,
    OAKLAND_HOUSE_RIGHT,
    OAKLAND_SCHOOL,
    OCEAN_BOTTOM_MIDDLE,
    OCEAN_BOTTOM_NEAR,
    PAMPAS_FAR,
    PUBLIC_FAR,
    PUBLIC_NEAR,
    RESIDENTIAL_FAR_LEFT,
    RESIDENTIAL_FAR_RIGHT,
    RESIDENTIAL_MIDDLE_LEFT,
    RESIDENTIAL_MIDDLE_RIGHT,
    RESIDENTIAL_NEAR_LEFT,
    RESIDENTIAL_NEAR_RIGHT,
    RICKSHAW_TOWN,
    ROLLER_COASTER,
    ROYCE_HALL,
    SCHOOL_BUNGALOW,
    ST_JOSEPHS_ANNEX,
    ST_JOSEPHS_CHURCH,
    TAIWAN_HOUSES_CENTRE,
    TAIWAN_HOUSE_FAR,
    TAIWAN_HOUSE_NEAR,
    TAIWAN_MOUNTAINS_BRIDGED,
    TAIWAN_MOUNTAIN_LEFT,
    TAIWAN_MOUNTAIN_RIGHT,
    TENNIS_COURT,
    VALLEY_FREEWAY
} from '../../../../constants/scene/things/flats'

import {
    CAMPUS__SHARED,
    BUILDINGS__SHARED,
    BUILDING__SHARED,
    HOUSE__SHARED,
    OAKLAND_HOUSE_LEFT__SHARED,
    OAKLAND_HOUSE_RIGHT__SHARED,
    TAIWAN_HOUSE__SHARED
} from '../../../sharedStyles/buildings'
import {
    FOLIAGE__SHARED,
    FREEWAY_SIGN__SHARED,
    GRAVE__SHARED,
    MOUNTAIN__SHARED,
    TRASH_CAN__SHARED
} from '../../../sharedStyles/outdoor'
import { ALL_VEHICLES__SHARED } from '../../../sharedStyles/vehicles'

export default {
    [BEDROOM_BUS]: ALL_VEHICLES__SHARED,
    [BEDROOM_SIREN]: null,
    [BERKELEY_BUILDING_TALL]: [
        CAMPUS__SHARED,
        BUILDING__SHARED
    ],
    [BERKELEY_BUILDING_WIDE]: [
        CAMPUS__SHARED,
        BUILDING__SHARED
    ],
    [CAMPANILE]: FOLIAGE__SHARED,
    [CEMETERY_HILLS_LEFT]: [
        FOLIAGE__SHARED,
        GRAVE__SHARED,
        MOUNTAIN__SHARED
    ],
    [CEMETERY_HILLS_RIGHT]: [
        FOLIAGE__SHARED,
        GRAVE__SHARED,
        MOUNTAIN__SHARED
    ],
    [CLIFF_GRAVES_FAR]: [
        GRAVE__SHARED,
        MOUNTAIN__SHARED
    ],
    [CLIFF_GRAVES_NEAR]: [
        GRAVE__SHARED,
        MOUNTAIN__SHARED
    ],
    [COMMERCIAL_CENTRE]: BUILDING__SHARED,
    [COMMERCIAL_FAR_LEFT]: BUILDING__SHARED,
    [COMMERCIAL_FAR_RIGHT]: BUILDING__SHARED,
    [COMMERCIAL_MIDDLE_LEFT]: BUILDING__SHARED,
    [COMMERCIAL_MIDDLE_RIGHT]: BUILDING__SHARED,
    [COMMERCIAL_NEAR_LEFT]: BUILDING__SHARED,
    [COMMERCIAL_NEAR_RIGHT]: BUILDING__SHARED,
    [DRIVING_HOUSE_LEFT]: [
        FOLIAGE__SHARED,
        BUILDING__SHARED
    ],
    [DRIVING_HOUSE_RIGHT]: [
        FOLIAGE__SHARED,
        BUILDING__SHARED
    ],
    [EL_CERRITO_FAR]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED
    ],
    [EL_CERRITO_NEAR]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [FAMILY_HOUSE]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [FERRIS_WHEEL]: null,
    [FOREBODING_TREES]: FOLIAGE__SHARED,
    [GO_KART_TRACK]: ALL_VEHICLES__SHARED,
    [NOHO_HOUSE_LEFT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        TRASH_CAN__SHARED
    ],
    [NOHO_HOUSE_RIGHT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [OAKLAND_FLAG]: null,
    [OAKLAND_HOUSE_LEFT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        OAKLAND_HOUSE_LEFT__SHARED
    ],
    [OAKLAND_HOUSE_RIGHT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        OAKLAND_HOUSE_RIGHT__SHARED
    ],
    [OAKLAND_SCHOOL]: [
        BUILDING__SHARED,
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [OCEAN_BOTTOM_MIDDLE]: null,
    [OCEAN_BOTTOM_NEAR]: null,
    [PAMPAS_FAR]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [PUBLIC_FAR]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [PUBLIC_NEAR]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [RESIDENTIAL_FAR_LEFT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [RESIDENTIAL_FAR_RIGHT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [RESIDENTIAL_MIDDLE_LEFT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        OAKLAND_HOUSE_RIGHT__SHARED
    ],
    [RESIDENTIAL_MIDDLE_RIGHT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [RESIDENTIAL_NEAR_LEFT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        OAKLAND_HOUSE_LEFT__SHARED
    ],
    [RESIDENTIAL_NEAR_RIGHT]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED
    ],
    [RICKSHAW_TOWN]: [
        FOLIAGE__SHARED,
        TAIWAN_HOUSE__SHARED
    ],
    [ROLLER_COASTER]: null,
    [ROYCE_HALL]: null,
    [SCHOOL_BUNGALOW]: [
        BUILDING__SHARED,
        HOUSE__SHARED
    ],
    [ST_JOSEPHS_ANNEX]: HOUSE__SHARED,
    [ST_JOSEPHS_CHURCH]: FOLIAGE__SHARED,
    [TAIWAN_HOUSES_CENTRE]: TAIWAN_HOUSE__SHARED,
    [TAIWAN_HOUSE_FAR]: TAIWAN_HOUSE__SHARED,
    [TAIWAN_HOUSE_NEAR]: TAIWAN_HOUSE__SHARED,
    [TAIWAN_MOUNTAINS_BRIDGED]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED,
        TAIWAN_HOUSE__SHARED
    ],
    [TAIWAN_MOUNTAIN_LEFT]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [TAIWAN_MOUNTAIN_RIGHT]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [TENNIS_COURT]: FOLIAGE__SHARED,
    [VALLEY_FREEWAY]: [
        BUILDINGS__SHARED,
        FREEWAY_SIGN__SHARED,
        FOLIAGE__SHARED
    ]
}
