export const BERKELEY_BUILDING__SHARED = 'berkeleyBuilding'
export const BUILDINGS__SHARED = 'buildings'
export const OAKLAND_HOUSE__SHARED = 'oaklandHouse'
export const OAKLAND_HOUSE_LEFT__SHARED = 'oaklandHouseLeft'
export const OAKLAND_HOUSE_RIGHT__SHARED = 'oaklandHouseRight'
export const OAKLAND_COMMERCIAL__SHARED = 'oaklandCommercial'
export const TAIWAN_HOUSE__SHARED = 'taiwanHouse'
export const WEDDING__SHARED = 'wedding'
