export const ESTHER_SPEECH_PANEL = 'estherSpeechPanel'
export const BATHTUB = 'bathtub'
export const BEDROOM_FENCE = 'bedroomFence'
export const BEDROOM_DESK = 'bedroomDesk'
export const CAPTAIN_BED = 'captainBed'
export const SCHOOLBUS_INTERIOR = 'schoolbusInterior'
export const SCHOOLBUS_EXTERIOR = 'schoolbusExterior'
export const OCEAN_CAVE_EXTERIOR = 'oceanCaveExterior'
export const OCEAN_CAVE_INTERIOR = 'oceanCaveInterior'
export const BENNETT_COUCH = 'bennettCouch'
export const BENNETT_LEFT_ARMREST = 'bennettLeftArmrest'
export const BENNETT_RIGHT_ARMREST = 'bennettRightArmrest'
export const GO_KART_EXTERIOR_LEFT = 'goKartExteriorLeft'
export const GO_KART_EXTERIOR_RIGHT = 'goKartExteriorRight' // Duplicate.
export const DISHROOM_SINK = 'dishroomSink'
export const BENNETT_BED = 'bennettBed'
export const WAITING_ARMCHAIR_BENNETT = 'waitingArmchairBennett'
export const WAITING_LEFT_ARMREST_BENNETT = 'waitingLeftArmrestBennett'
export const WAITING_RIGHT_ARMREST_BENNETT = 'waitingRightArmrestBennett'
export const WAITING_ARMCHAIR_LIZ = 'waitingArmchairLiz' // Duplicate.
export const WAITING_LEFT_ARMREST_LIZ = 'waitingLeftArmrestLiz' // Duplicate.
export const WAITING_RIGHT_ARMREST_LIZ = 'waitingRightArmrestLiz' // Duplicate.
export const LIZ_BED = 'lizBed'
export const SATURN_INTERIOR = 'saturnInterior'
export const SATURN_EXTERIOR = 'saturnExterior'
export const ATTIC_COUCH = 'atticCouch'
export const ATTIC_LEFT_ARMREST = 'atticLeftArmrest'
export const ATTIC_RIGHT_ARMREST = 'atticRightArmrest'
export const LIZ_COUCH = 'lizCouch'
export const VOLKSWAGEN = 'volkswagen'
export const BENNETT_COUCH_BUBBLE = 'bennettCouchBubble' // Duplicate.
export const BENNETT_LEFT_ARMREST_BUBBLE = 'bennettLeftArmrestBubble' // Duplicate.
export const BENNETT_RIGHT_ARMREST_BUBBLE = 'bennettRightArmrestBubble' // Duplicate.
export const SNOWGLOBE_TETHERBALL = 'snowglobeTetherball'
export const SNOWGLOBE_LIZ_ALONE = 'snowglobeLizAlone' // Duplicate.
export const SNOWGLOBE_BENNETT_MIRIAM = 'snowglobeBennettMiriam' // Duplicate.
export const SNOWGLOBE_LIZ_KHARI = 'snowglobeLizKhari' // Duplicate.
export const SNOWGLOBE_BENNETT_ALONE = 'snowglobeBennettAlone' // Duplicate.
export const REATTA_INTERIOR = 'reattaInterior'
export const REATTA_EXTERIOR = 'reattaExterior'
export const HOSPITAL_BED = 'hospitalBed'
export const DEATHBED_THOUGHT_PANEL = 'deathbedThoughtPanel'
export const TENNIS_THOUGHT_PANEL = 'tennisThoughtPanel'
export const PHONE_CALL_PANEL = 'phoneCallPanel'
export const WEDDING_PLATFORM = 'weddingPlatform'
export const INVERSE_THOUGHT_PANEL = 'inverseThoughtBackdrop'
