export const ESTHER_SPEECH_PANEL = 'estherSpeechPanel'
export const BATHTUB = 'bathtub'
export const BEDROOM_FENCE = 'bedroomFence'
export const SCHOOLBUS_INTERIOR = 'schoolbusInterior'
export const SCHOOLBUS_EXTERIOR = 'schoolbusExterior'
export const OCEAN_CAVE_EXTERIOR = 'oceanCaveExterior'
export const OCEAN_CAVE_INTERIOR = 'oceanCaveInterior'
export const GO_KART_LEFT_EXTERIOR = 'goKartExteriorLeft'
export const GO_KART_RIGHT_EXTERIOR = 'goKartExteriorRight' // Duplicate.
export const DISHROOM_SINK = 'dishroomSink'
export const SATURN_INTERIOR = 'saturnInterior'
export const SATURN_EXTERIOR = 'saturnExterior'
export const VOLKSWAGEN = 'volkswagen'
export const SNOWGLOBE_TETHERBALL = 'snowglobeTetherball'
export const SNOWGLOBE_LIZ_ALONE = 'snowglobeLizAlone' // Duplicate.
export const SNOWGLOBE_BENNETT_MIRIAM = 'snowglobeBennettMiriam' // Duplicate.
export const SNOWGLOBE_LIZ_KHARI = 'snowglobeLizKhari' // Duplicate.
export const SNOWGLOBE_BENNETT_ALONE = 'snowglobeBennettAlone' // Duplicate.
export const REATTA_INTERIOR = 'reattaInterior'
export const REATTA_EXTERIOR = 'reattaExterior'
export const DEATHBED_THOUGHT_PANEL = 'deathbedThoughtPanel'
export const TENNIS_THOUGHT_PANEL = 'tennisThoughtPanel'
export const PHONE_CALL_PANEL = 'phoneCallPanel'
export const WEDDING_PLATFORM = 'weddingPlatform'
export const INVERSE_THOUGHT_PANEL = 'inverseThoughtBackdrop'

// TODO
export const CAPTAIN_BED_PANEL = 'captainBedPanel'
export const BENNETT_BED_PANEL = 'bennettBedPanel'
export const LIZ_BED_PANEL = 'lizBedPanel'
export const HOSPITAL_BED_PANEL = 'hospitalBedPanel'
