export const ALL_VEHICLES__SHARED = 'allVehicles'
export const INTERIOR__SHARED = 'interior'
export const REATTA__SHARED = 'reatta'
export const SATURN__SHARED = 'saturn'
export const SCHOOLBUS__SHARED = 'schoolbus'
