import {
    YOUNG_BENNETT,
    BENNETT_STEPHANIE,
    ANITA,
    ESTHER,
    WILLY
} from '../../actorKeys'

import ARRANGEMENTS_YOUNG_BENNETT from './actors/youngBennett'
import ARRANGEMENTS_BENNETT_STEPHANIE from './actors/bennettStephanie'
import ARRANGEMENTS_ANITA from './actors/anita'
import ARRANGEMENTS_ESTHER from './actors/esther'
import ARRANGEMENTS_WILLY from './actors/willy'

const ARRANGEMENTS_ACTORS = {
    [YOUNG_BENNETT]: ARRANGEMENTS_YOUNG_BENNETT,
    [BENNETT_STEPHANIE]: ARRANGEMENTS_BENNETT_STEPHANIE,
    [ANITA]: ARRANGEMENTS_ANITA,
    [ESTHER]: ARRANGEMENTS_ESTHER,
    [WILLY]: ARRANGEMENTS_WILLY
}

export default ARRANGEMENTS_ACTORS
