import {
    ESTHER_SPEECH,
    SKETCHBOOK__TOGETHER,
    TOGETHER_SKETCH,
    BUBBLE_SMALL__LEFT,
    BUBBLE_MEDIUM__LEFT,
    BUBBLE_LARGE__LEFT,
    THOUGHT_LARGE__LEFT,
    BUBBLE_SMALL__RIGHT,
    BUBBLE_MEDIUM__RIGHT,
    BUBBLE_LARGE__RIGHT,
    THOUGHT_LARGE__RIGHT,
    SKETCHBOOK__APART,
    APART_SKETCH,
    SKETCHBOOK__DOGS,
    DOGS_SKETCH,
    SKETCHBOOK__ESCAPE_POD,
    ESCAPE_POD_SKETCH,
    BUBBLE_SMALL__CINEMA,
    BUBBLE_MEDIUM__CINEMA,
    BUBBLE_LARGE__CINEMA,
    CINEMA_THOUGHT_RECORDING,
    CINEMA_THOUGHT_BUYING,
    BUBBLE_SMALL__GO_KART,
    BUBBLE_MEDIUM__GO_KART,
    GO_KART_THOUGHT,
    BUBBLE_SMALL__WAITING,
    BUBBLE_MEDIUM__WAITING,
    BUBBLE_LARGE__WAITING,
    WAITING_THOUGHT_WALKING,
    WAITING_THOUGHT_SINGING,
    WAITING_THOUGHT_STUDYING,
    PHARMACY_CEL,
    TARPIT_CONSTELLATION,
    SIBLING_CONSTELLATION,
    KHARI_ATTACK_SPEECH,
    LIZ_DEFENCE_SPEECH,
    BUBBLE_SMALL__LIZ,
    BUBBLE_MEDIUM__LIZ,
    BUBBLE_LARGE__LIZ,
    LIZ_THOUGHT,
    BUBBLE_SMALL__DEATHBED,
    BUBBLE_MEDIUM__DEATHBED,
    BUBBLE_LARGE__DEATHBED,
    BUBBLE_SMALL__INVERSE,
    BUBBLE_MEDIUM__INVERSE,
    BUBBLE_LARGE__INVERSE,
    THOUGHT_MEDIUM,
    BUBBLE_SMALL__TENNIS,
    BUBBLE_MEDIUM__TENNIS,
    BUBBLE_LARGE__TENNIS,
    THOUGHT_SMALL
} from '../../../../constants/scene/things/bubbles'

import {
    AMY,
    BENNETT,
    LIZ,
    MARA
} from '../../../../constants/scene/actors'
import { ALL_PEOPLE__SHARED } from '../../../sharedStyles/people'
import { BUBBLE__SHARED } from '../../../sharedStyles/props'
import {
    ACOUSTIC_GUITAR__SHARED,
    BANJO__SHARED,
    HEADPHONE__SHARED,
    MICROPHONE__SHARED,
    MONITOR__SHARED
} from '../../../sharedStyles/instruments'
import {
    BOOK__SHARED,
    SKETCHBOOK__SHARED
} from '../../../sharedStyles/paper'
import {
    SKETCH_DOGS__SHARED,
    SKETCH_PEOPLE__SHARED
} from '../../../sharedStyles/sketch'

export default {
    [ESTHER_SPEECH]: null,
    [SKETCHBOOK__TOGETHER]: [
        BOOK__SHARED,
        SKETCHBOOK__SHARED
    ],
    [TOGETHER_SKETCH]: SKETCH_PEOPLE__SHARED,
    [BUBBLE_SMALL__LEFT]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__LEFT]: BUBBLE__SHARED,
    [BUBBLE_LARGE__LEFT]: BUBBLE__SHARED,
    [THOUGHT_LARGE__LEFT]: BUBBLE__SHARED,
    [BUBBLE_SMALL__RIGHT]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__RIGHT]: BUBBLE__SHARED,
    [BUBBLE_LARGE__RIGHT]: BUBBLE__SHARED,
    [THOUGHT_LARGE__RIGHT]: BUBBLE__SHARED,
    [SKETCHBOOK__APART]: [
        BOOK__SHARED,
        SKETCHBOOK__SHARED
    ],
    [APART_SKETCH]: SKETCH_PEOPLE__SHARED,
    [SKETCHBOOK__DOGS]: [
        BOOK__SHARED,
        SKETCHBOOK__SHARED
    ],
    [DOGS_SKETCH]: SKETCH_DOGS__SHARED,
    [SKETCHBOOK__ESCAPE_POD]: [
        BOOK__SHARED,
        SKETCHBOOK__SHARED
    ],
    [ESCAPE_POD_SKETCH]: SKETCH_DOGS__SHARED,
    [BUBBLE_SMALL__CINEMA]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__CINEMA]: BUBBLE__SHARED,
    [BUBBLE_LARGE__CINEMA]: BUBBLE__SHARED,
    [CINEMA_THOUGHT_RECORDING]: [
        ACOUSTIC_GUITAR__SHARED,
        HEADPHONE__SHARED,
        MICROPHONE__SHARED,
        BENNETT,
        ALL_PEOPLE__SHARED
    ],
    [CINEMA_THOUGHT_BUYING]: [
        MARA,
        ALL_PEOPLE__SHARED
    ],
    [BUBBLE_SMALL__GO_KART]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__GO_KART]: BUBBLE__SHARED,
    [GO_KART_THOUGHT]: null,
    [BUBBLE_SMALL__WAITING]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__WAITING]: BUBBLE__SHARED,
    [BUBBLE_LARGE__WAITING]: BUBBLE__SHARED,
    [WAITING_THOUGHT_WALKING]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [WAITING_THOUGHT_SINGING]: [
        BANJO__SHARED,
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [WAITING_THOUGHT_STUDYING]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [PHARMACY_CEL]: null,
    [TARPIT_CONSTELLATION]: null,
    [SIBLING_CONSTELLATION]: SKETCH_PEOPLE__SHARED,
    [KHARI_ATTACK_SPEECH]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [LIZ_DEFENCE_SPEECH]: [
        BANJO__SHARED,
        ACOUSTIC_GUITAR__SHARED,
        MICROPHONE__SHARED,
        MONITOR__SHARED,
        AMY,
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [BUBBLE_SMALL__LIZ]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__LIZ]: BUBBLE__SHARED,
    [BUBBLE_LARGE__LIZ]: BUBBLE__SHARED,
    [LIZ_THOUGHT]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [BUBBLE_SMALL__DEATHBED]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__DEATHBED]: BUBBLE__SHARED,
    [BUBBLE_LARGE__DEATHBED]: BUBBLE__SHARED,
    [BUBBLE_SMALL__INVERSE]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__INVERSE]: BUBBLE__SHARED,
    [BUBBLE_LARGE__INVERSE]: BUBBLE__SHARED,
    [THOUGHT_MEDIUM]: BUBBLE__SHARED,
    [BUBBLE_SMALL__TENNIS]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM__TENNIS]: BUBBLE__SHARED,
    [BUBBLE_LARGE__TENNIS]: BUBBLE__SHARED,
    [THOUGHT_SMALL]: BUBBLE__SHARED
}
