import {
    ESTHER_SPEECH,
    TOGETHER_SKETCH,
    APART_SKETCH,
    DOGS_SKETCH,
    ESCAPE_POD_SKETCH,
    CINEMA_THOUGHT_RECORDING,
    CINEMA_THOUGHT_BUYING,
    GO_KART_THOUGHT,
    WAITING_THOUGHT_WALKING,
    WAITING_THOUGHT_SINGING,
    WAITING_THOUGHT_STUDYING,
    PHARMACY_CEL,
    TARPIT_CONSTELLATION,
    SIBLING_CONSTELLATION,
    KHARI_ATTACK_SPEECH,
    LIZ_DEFENCE_SPEECH,
    LIZ_THOUGHT,
    THOUGHT_MEDIUM,
    THOUGHT_SMALL,

    THOUGHT_LARGE,
    SKETCHBOOK,
    BUBBLE_SMALL,
    BUBBLE_MEDIUM,
    BUBBLE_LARGE
} from '../../../../constants/scene/things/bubbles'

import {
    AMY,
    BENNETT,
    LIZ,
    MARA
} from '../../../../constants/scene/actors'
import { ALL_PEOPLE__SHARED } from '../../../sharedStyles/people'
import { BUBBLE__SHARED } from '../../../sharedStyles/props'
import {
    ACOUSTIC_GUITAR__SHARED,
    BANJO__SHARED,
    HEADPHONE__SHARED,
    MICROPHONE__SHARED,
    MONITOR__SHARED
} from '../../../sharedStyles/instruments'
import {
    BOOK__SHARED,
    SKETCHBOOK__SHARED
} from '../../../sharedStyles/paper'
import {
    SKETCH_DOGS__SHARED,
    SKETCH_PEOPLE__SHARED
} from '../../../sharedStyles/sketch'

export default {
    [ESTHER_SPEECH]: null,
    [TOGETHER_SKETCH]: SKETCH_PEOPLE__SHARED,
    [APART_SKETCH]: SKETCH_PEOPLE__SHARED,
    [DOGS_SKETCH]: SKETCH_DOGS__SHARED,
    [ESCAPE_POD_SKETCH]: SKETCH_DOGS__SHARED,
    [CINEMA_THOUGHT_RECORDING]: [
        ACOUSTIC_GUITAR__SHARED,
        HEADPHONE__SHARED,
        MICROPHONE__SHARED,
        BENNETT,
        ALL_PEOPLE__SHARED
    ],
    [CINEMA_THOUGHT_BUYING]: [
        MARA,
        ALL_PEOPLE__SHARED
    ],
    [GO_KART_THOUGHT]: null,
    [WAITING_THOUGHT_WALKING]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [WAITING_THOUGHT_SINGING]: [
        BANJO__SHARED,
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [WAITING_THOUGHT_STUDYING]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [PHARMACY_CEL]: null,
    [TARPIT_CONSTELLATION]: null,
    [SIBLING_CONSTELLATION]: SKETCH_PEOPLE__SHARED,
    [KHARI_ATTACK_SPEECH]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [LIZ_DEFENCE_SPEECH]: [
        BANJO__SHARED,
        ACOUSTIC_GUITAR__SHARED,
        MICROPHONE__SHARED,
        MONITOR__SHARED,
        AMY,
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [LIZ_THOUGHT]: [
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [THOUGHT_SMALL]: BUBBLE__SHARED,
    [THOUGHT_MEDIUM]: BUBBLE__SHARED,

    [THOUGHT_LARGE]: BUBBLE__SHARED,
    [SKETCHBOOK]: [
        BOOK__SHARED,
        SKETCHBOOK__SHARED
    ],
    [BUBBLE_SMALL]: BUBBLE__SHARED,
    [BUBBLE_MEDIUM]: BUBBLE__SHARED,
    [BUBBLE_LARGE]: BUBBLE__SHARED
}
