import {
    BENNETT,
    LIZ,
    KHARI,
    BENNETT_REFLECTION,
    LIZ_REFLECTION,
    KHARI_REFLECTION
} from '../../actorKeys'

import ARRANGEMENTS_BENNETT from './actors/bennett'
import ARRANGEMENTS_LIZ from './actors/liz'
import ARRANGEMENTS_KHARI from './actors/khari'
import ARRANGEMENTS_BENNETT_REFLECTION from './actors/bennettReflection'
import ARRANGEMENTS_LIZ_REFLECTION from './actors/lizReflection'
import ARRANGEMENTS_KHARI_REFLECTION from './actors/khariReflection'

const ARRANGEMENTS_ACTORS = {
    [BENNETT]: ARRANGEMENTS_BENNETT,
    [LIZ]: ARRANGEMENTS_LIZ,
    [KHARI]: ARRANGEMENTS_KHARI,
    [BENNETT_REFLECTION]: ARRANGEMENTS_BENNETT_REFLECTION,
    [LIZ_REFLECTION]: ARRANGEMENTS_LIZ_REFLECTION,
    [KHARI_REFLECTION]: ARRANGEMENTS_KHARI_REFLECTION
}

export default ARRANGEMENTS_ACTORS
