import {
    BENNETT,
    LIZ,
    KHARI_LIZ,
    BENNETT_REFLECTION,
    LIZ_REFLECTION,
    KHARI_LIZ_REFLECTION
} from '../../actorKeys'

import ARRANGEMENTS_BENNETT from './actors/bennett'
import ARRANGEMENTS_LIZ from './actors/liz'
import ARRANGEMENTS_KHARI_LIZ from './actors/khariLiz'
import ARRANGEMENTS_BENNETT_REFLECTION from './actors/bennettReflection'
import ARRANGEMENTS_LIZ_REFLECTION from './actors/lizReflection'
import ARRANGEMENTS_KHARI_LIZ_REFLECTION from './actors/khariLizReflection'

const ARRANGEMENTS_ACTORS = {
    [BENNETT]: ARRANGEMENTS_BENNETT,
    [LIZ]: ARRANGEMENTS_LIZ,
    [KHARI_LIZ]: ARRANGEMENTS_KHARI_LIZ,
    [BENNETT_REFLECTION]: ARRANGEMENTS_BENNETT_REFLECTION,
    [LIZ_REFLECTION]: ARRANGEMENTS_LIZ_REFLECTION,
    [KHARI_LIZ_REFLECTION]: ARRANGEMENTS_KHARI_LIZ_REFLECTION
}

export default ARRANGEMENTS_ACTORS
