export const ATTIC_LINENS__SHARED = 'atticLinens'
export const BENNETT_LINENS__SHARED = 'bennettLinens'
export const HOSPITAL_LINENS__SHARED = 'hospitalLinens'
export const LIZ_LINENS__SHARED = 'lizLinens'
export const MIRIAM_LINENS__SHARED = 'miriamLinens'
export const TAIWAN_LINENS__SHARED = 'taiwanLinens'
export const WAITING_ARMCHAIR__SHARED = 'waitingArmchair'
