import {
    BENNETT_FATHER,
    MOTHER,
    MIRIAM_STEPHANIE
} from '../../keys'

import ARRANGEMENTS_BENNETT_FATHER from './actors/bennettFather'
import ARRANGEMENTS_MOTHER from './actors/mother'
import ARRANGEMENTS_MIRIAM_STEPHANIE from './actors/miriamStephanie'

const ARRANGEMENTS_ACTORS = {
    [BENNETT_FATHER]: ARRANGEMENTS_BENNETT_FATHER,
    [MOTHER]: ARRANGEMENTS_MOTHER,
    [MIRIAM_STEPHANIE]: ARRANGEMENTS_MIRIAM_STEPHANIE
}

export default ARRANGEMENTS_ACTORS
