export const OCEAN_LIFE__SHARED = 'oceanLife'
export const ODIN_GHOST__SHARED = 'odinGhost'
export const ODIN_PAST__SHARED = 'odinPast'
export const OPAL__SHARED = 'opal'
export const OPAL_PRESENT__SHARED = 'opalPresent'
export const OPAL_FUTURE__SHARED = 'opalFuture'
export const PEAFOWL__SHARED = 'peafowl'
export const SEA_SERPENT__SHARED = 'seaSerpent'
