export const BASEMENT_TAKEOUT__SHARED = 'basementTakeout__shared'
export const BUDWEISER__SHARED = 'budweiser__shared'
export const CHINESE_TAKEOUT__SHARED = 'chineseTakeout__shared'
export const EVIAN__SHARED = 'evian__shared'
export const GARBAGE_BAG__SHARED = 'garbageBag__shared'
export const ROBITUSSIN__SHARED = 'robitussin__shared'
