export const BASEMENT_TAKEOUT__SHARED = 'basementTakeout'
export const BUDWEISER__SHARED = 'budweiser'
export const CHINESE_TAKEOUT__SHARED = 'chineseTakeout'
export const EVIAN__SHARED = 'evian'
export const GARBAGE_BAG__SHARED = 'garbageBag'
export const HEINEKEN__SHARED = 'heineken'
export const LANCET_PEN__SHARED = 'lancetPen'
export const ROBITUSSIN__SHARED = 'robitussin'
