module.exports = {
    ARROW_LEFT: 'ArrowLeft',
    ARROW_RIGHT: 'ArrowRight',
    ARROW_UP: 'ArrowUp',
    ARROW_DOWN: 'ArrowDown',
    CAPS_LOCK: 'CapsLock',
    PAGE_UP: 'PageUp',
    PAGE_DOWN: 'PageDown',
    ENTER: 'Enter',
    ESCAPE: 'Escape',
    SPACE: ' ',
    TAB: 'Tab',

    ADMIN_TOGGLE_KEY: 'a',
    AUDIO_PLAY_KEY: 'p',
    AUDIO_OPTIONS_TOGGLE_KEY: 'o',
    AUDIO_PREVIOUS_SONG_KEY: 'j',
    AUDIO_NEXT_SONG_KEY: 'k',
    AUDIO_REWIND_KEY: 'r',
    AUDIO_FAST_FORWARD_KEY: 'f',
    CAROUSEL_TOGGLE_KEY: 'c',
    DOTS_SECTION_EXPAND_KEY: 'd',
    LYRIC_COLUMN_TOGGLE_KEY: 'e',
    LYRIC_SECTION_EXPAND_KEY: 'l',
    SCENE_REWIND_KEY: 'n',
    SCENE_FORWARD_KEY: 'm',
    OVERVIEW_TOGGLE_KEY: 'b',
    SCORE_TOGGLE_KEY: 's',
    TIPS_TOGGLE_KEY: 't',
    TITLE_TOGGLE_KEY: 'i'
}
