// Constants prefixed with LS *must* be the same in Less.

const

/*****************
 * BUTTON VALUES *
 *****************/

// These values *must* be the same in less.
LS_LENGTH_ICON = 44,
APP_MINI_LARGE_ICON_DIAMETER = 47,
APP_TABLET_LARGE_ICON_DIAMETER = 50,
APP_LARGE_ICON_DIAMETER = 54,
APP_THIN_MARGIN = 4,

/**************
 * NAV VALUES *
 **************/

// These values *must* be the same in less.
NAV_BOOK_PADDING = APP_THIN_MARGIN,
NAV_LAST_TITLE_MARGIN = 50,
NAV_HEIGHT_PADDING = 6,
NAV_BOOK_HEIGHT = LS_LENGTH_ICON + NAV_HEIGHT_PADDING,

// Less files do not know these values.
SHRINK_ICON_DIAMETER = 36,
DOUBLE_COLUMN_UNITS = 26,
SINGLE_COLUMN_UNITS = 16,

DOUBLE_COLUMN_STATIC_BREAKPOINT = 20 * LS_LENGTH_ICON + 10 * NAV_BOOK_PADDING + DOUBLE_COLUMN_UNITS,
DOUBLE_COLUMN_SHRINK_BREAKPOINT = 20 * SHRINK_ICON_DIAMETER + 10 * NAV_BOOK_PADDING + DOUBLE_COLUMN_UNITS,
SINGLE_COLUMN_STATIC_BREAKPOINT = 11 * LS_LENGTH_ICON + 8 * NAV_BOOK_PADDING + SINGLE_COLUMN_UNITS,

/***************
 * MENU VALUES *
 ***************/

LS_HEIGHT_MENU = 72,
LS_MARGIN_MENU_CHILD = 10,
LS_MARGIN_MENU_CHILD_NARROW = 3,

LS_HEIGHT_MENU_TOP_ROW_PHONE =
    LS_LENGTH_ICON +
    LS_MARGIN_MENU_CHILD_NARROW * 2,

LS_MINWIDTH_CHILD_TITLE = 72,

LS_HEIGHT_AUDIO = 64,
LS_HEIGHT_AUDIO_BANNER_BOTTOM_ROW =
    LS_HEIGHT_AUDIO / 2,
LS_HEIGHT_AUDIO_SLIDER_BOTTOM_ROW =
    LS_HEIGHT_AUDIO / 2,

LS_HEIGHT_ABOVE_OVERLAY_PHONE =
    LS_HEIGHT_MENU_TOP_ROW_PHONE +
    LS_HEIGHT_AUDIO_SLIDER_BOTTOM_ROW,

LS_HEIGHT_MENU_PHONE =
    LS_HEIGHT_ABOVE_OVERLAY_PHONE +
    LS_HEIGHT_AUDIO_BANNER_BOTTOM_ROW,

/****************
 * AUDIO VALUES *
 ****************/

// These values *must* be the same in less.
AUDIO_BLOCK_PADDING = 12,
AUDIO_BUTTON_MARGIN = 3,
AUDIO_OPTION_BUTTON_MARGIN = 8,
AUDIO_BANNER_MIN_WIDTH = 220,

AUDIO_CONSTANT = AUDIO_BANNER_MIN_WIDTH + 3 * AUDIO_BLOCK_PADDING + 3 * LS_LENGTH_ICON + 2 * AUDIO_BUTTON_MARGIN + AUDIO_OPTION_BUTTON_MARGIN,

/**********************
 * SCORES TIPS VALUES *
 **********************/

// These values *must* be the same in less.
SCORES_TIPS_PADDING = APP_THIN_MARGIN,
SCORES_TIPS_MARGIN = 10,

SCORES_TIPS_CONSTANT = 2 * SCORES_TIPS_PADDING + SCORES_TIPS_MARGIN,

SCORES_TIPS_IN_MAIN_CONSTANT = LS_MINWIDTH_CHILD_TITLE + AUDIO_CONSTANT + SCORES_TIPS_CONSTANT,
TITLE_IN_AUDIO_BREAKPOINT = AUDIO_CONSTANT + SCORES_TIPS_CONSTANT + 2 * LS_MARGIN_MENU_CHILD_NARROW + 3 * APP_MINI_LARGE_ICON_DIAMETER,

// This value *must* be the same in less.
COLLAPSED_LYRIC_SECTION_HEIGHT = 0.32,

// This value *must* be the same in less.
POPUP_CONTENT_SIDE_PADDING = 20,

WIKI_SIDE_PADDING_TOTAL = POPUP_CONTENT_SIDE_PADDING * 2 + APP_LARGE_ICON_DIAMETER * 2,

/*******************
 * CAROUSEL VALUES *
 *******************/

// This value *must* be the same in less.
// FIXME: Not great that this value is hard-coded.
CAROUSEL_ANNOTATION_MIN_WIDTH = 406,

/************************
 * DEVICE WIDTH OBJECTS *
 ************************/

// These values *must* be the same in less.
GOLDEN_CORD_WIDTH = 745,
UNCANNY_VALLEY_WIDTH = 570,

PHONE_WIDTH = '_phone_',
MINI_WIDTH = '_mini_',
TABLET_WIDTH = '_tablet_',
LAPTOP_WIDTH = '_laptop_',
MONITOR_WIDTH = '_monitor_',

// These max width values *must* be the same in less.
PHONE_OBJECT = {
    className: PHONE_WIDTH,
    maxWidth: 475
},
MINI_OBJECT = {
    className: MINI_WIDTH,
    maxWidth: 720,
    singleColumnStaticBreakpoint: SINGLE_COLUMN_STATIC_BREAKPOINT + APP_MINI_LARGE_ICON_DIAMETER,
    isScoresTipsInMainBreakpoint: SCORES_TIPS_IN_MAIN_CONSTANT + 2 * LS_MARGIN_MENU_CHILD_NARROW + 3 * APP_MINI_LARGE_ICON_DIAMETER,
    isTitleInAudioBreakpoint: TITLE_IN_AUDIO_BREAKPOINT
},
TABLET_OBJECT = {
    className: TABLET_WIDTH,
    maxWidth: 1100,
    doubleColumnStaticBreakpoint: DOUBLE_COLUMN_STATIC_BREAKPOINT + APP_TABLET_LARGE_ICON_DIAMETER,
    doubleColumnShrinkBreakpoint: DOUBLE_COLUMN_SHRINK_BREAKPOINT + APP_TABLET_LARGE_ICON_DIAMETER,
    singleColumnStaticBreakpoint: SINGLE_COLUMN_STATIC_BREAKPOINT + APP_TABLET_LARGE_ICON_DIAMETER
},
LAPTOP_OBJECT = {
    className: LAPTOP_WIDTH,
    maxWidth: 1400,
    singleColumnStaticBreakpoint: SINGLE_COLUMN_STATIC_BREAKPOINT + NAV_LAST_TITLE_MARGIN + UNCANNY_VALLEY_WIDTH + APP_LARGE_ICON_DIAMETER
    // NOTE: Laptop will now always have scores tips section in main column.
    // isScoresTipsInMainBreakpoint: SCORES_TIPS_IN_MAIN_CONSTANT + 2 * LS_MARGIN_MENU_CHILD_NARROW + UNCANNY_VALLEY_WIDTH + 3 * APP_LARGE_ICON_DIAMETER
},
MONITOR_OBJECT = {
    className: MONITOR_WIDTH,
    doubleColumnStaticBreakpoint: DOUBLE_COLUMN_STATIC_BREAKPOINT + NAV_LAST_TITLE_MARGIN + GOLDEN_CORD_WIDTH + APP_LARGE_ICON_DIAMETER,
    doubleColumnShrinkBreakpoint: DOUBLE_COLUMN_SHRINK_BREAKPOINT + NAV_LAST_TITLE_MARGIN + GOLDEN_CORD_WIDTH + APP_LARGE_ICON_DIAMETER,
    singleColumnStaticBreakpoint: SINGLE_COLUMN_STATIC_BREAKPOINT + NAV_LAST_TITLE_MARGIN + GOLDEN_CORD_WIDTH + APP_LARGE_ICON_DIAMETER,
    isScoresTipsInMainBreakpoint: SCORES_TIPS_IN_MAIN_CONSTANT + 2 * LS_MARGIN_MENU_CHILD + GOLDEN_CORD_WIDTH + 3 * APP_LARGE_ICON_DIAMETER
}

module.exports = {
    PHONE_WIDTH,
    MINI_WIDTH,
    TABLET_WIDTH,
    LAPTOP_WIDTH,
    MONITOR_WIDTH,

    PHONE_OBJECT,
    MINI_OBJECT,
    TABLET_OBJECT,
    LAPTOP_OBJECT,
    MONITOR_OBJECT,

    LS_LENGTH_ICON,
    APP_MINI_LARGE_ICON_DIAMETER,
    APP_TABLET_LARGE_ICON_DIAMETER,
    APP_LARGE_ICON_DIAMETER,
    APP_THIN_MARGIN,

    // Used for admin purposes.
    DEVICE_OBJECTS: [
        PHONE_OBJECT,
        MINI_OBJECT,
        TABLET_OBJECT,
        LAPTOP_OBJECT,
        MONITOR_OBJECT,
    ],

    COLLAPSED_LYRIC_SECTION_HEIGHT,
    HEIGHTLESS_LYRIC_MIN: 540,
    HEIGHTLESS_LYRIC_MAX: 720,

    LS_HEIGHT_MENU,
    LS_HEIGHT_MENU_PHONE,
    LS_HEIGHT_ABOVE_OVERLAY_PHONE,

    HIDDEN_NAV_MIN: 400,
    WIKI_SIDE_PADDING_TOTAL,

    NAV_BOOK_HEIGHT,

    STAGE_ASPECT_RATIO: 1.2,

    CAROUSEL_ANNOTATION_MIN_WIDTH,
    GOLDEN_CORD_WIDTH,
    UNCANNY_VALLEY_WIDTH
}
