import {
    JOHNNY_HORTON_ALBUM,
    TINTIN_POSTER,
    BENNETT_TAIWAN_STAIRS,
    ODIN_TAIWAN_STAIRS,
    BENNETT_TAIWAN_GATE,
    ODIN_TAIWAN_GATE,
    BENNETT_ODIN_RICKSHAW,
    BENNETT_SHORE,
    ODIN_SHORE,
    BENNETT_ODIN_BUOY,
    BENNETT_ODIN_DEPTHS,
    SEA_SERPENT_LEFT,
    SEA_SERPENT_RIGHT,
    BENNETT_ODIN_OCEAN_FLOOR,
    BENNETT_MAT,
    ODIN_MAT,
    BLOOM_COUNTY_POSTER,
    PCHELKA_MUSHKA_ROCKET,
    EARTH,
    SPACE_COLONY,
    VAN_NUYS_LOGO,
    CORKBOARD,
    POLICE_ALBUM,
    NIRVANA_POSTER,
    LEONARD_COHEN_POSTER,
    TELEVISION_ALBUM,
    PROGRESS_CHART_EARLY,
    PROGRESS_CHART_LATE,
    MARA_MEMENTO_POSTER,
    MARA_GLADIATOR_POSTER,
    GLADIATOR_POSTER,
    CODE_BOX,
    CLIPBOARD,
    PAINTING,
    NAS_ALBUM,
    ELLIOTT_SMITH_POSTER,
    SNOWGLOBE_PAST,
    SNOWGLOBE_PRESENT,
    SNOWGLOBE_FUTURE_CORD,
    SNOWGLOBE_FUTURE_REATTA,

    MARQUEE_FRAME,
    SNOWGLOBE_SMALL
} from '../../../../constants/scene/things/cardboards'

import {
    BENNETT,
    CHRISTOPHER,
    LIZ,
    MARA,
    MIRIAM
} from '../../../../constants/scene/actors'
import { ALL_PEOPLE__SHARED } from '../../../sharedStyles/people'
import { ODIN__SHARED } from '../../../sharedStyles/animals'
import {
    POSTER_GLADIATOR__SHARED,
    PROGRESS_CHART__SHARED
} from '../../../sharedStyles/print'
import { SNOWGLOBE__SHARED } from '../../../sharedStyles/props'
import {
    TAIWAN_BUOY__SHARED,
    TAIWAN_RICKSHAW__SHARED,
    TAIWAN_PILLOW__SHARED
} from '../../../sharedStyles/taiwan'
import { REATTA__SHARED } from '../../../sharedStyles/vehicles'

export default {
    [JOHNNY_HORTON_ALBUM]: ALL_PEOPLE__SHARED,
    [TINTIN_POSTER]: ALL_PEOPLE__SHARED,
    [BENNETT_TAIWAN_STAIRS]: [
        ALL_PEOPLE__SHARED,
        BENNETT
    ],
    [ODIN_TAIWAN_STAIRS]: ODIN__SHARED,
    [BENNETT_TAIWAN_GATE]: [
        ALL_PEOPLE__SHARED,
        BENNETT
    ],
    [ODIN_TAIWAN_GATE]: ODIN__SHARED,
    [BENNETT_ODIN_RICKSHAW]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        ODIN__SHARED,
        TAIWAN_RICKSHAW__SHARED
    ],
    [BENNETT_SHORE]: [
        ALL_PEOPLE__SHARED,
        BENNETT
    ],
    [ODIN_SHORE]: ODIN__SHARED,
    [BENNETT_ODIN_BUOY]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        ODIN__SHARED,
        TAIWAN_BUOY__SHARED
    ],
    [BENNETT_ODIN_DEPTHS]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        ODIN__SHARED
    ],
    [SEA_SERPENT_LEFT]: null,
    [SEA_SERPENT_RIGHT]: null,
    [BENNETT_ODIN_OCEAN_FLOOR]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        ODIN__SHARED
    ],
    [BENNETT_MAT]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        TAIWAN_PILLOW__SHARED
    ],
    [ODIN_MAT]: ODIN__SHARED,
    [BLOOM_COUNTY_POSTER]: ALL_PEOPLE__SHARED,
    [PCHELKA_MUSHKA_ROCKET]: null,
    [EARTH]: null,
    [SPACE_COLONY]: null,
    [VAN_NUYS_LOGO]: null,
    [CORKBOARD]: null,
    [POLICE_ALBUM]: null,
    [NIRVANA_POSTER]: ALL_PEOPLE__SHARED,
    [LEONARD_COHEN_POSTER]: ALL_PEOPLE__SHARED,
    [TELEVISION_ALBUM]: ALL_PEOPLE__SHARED,
    [PROGRESS_CHART_EARLY]: PROGRESS_CHART__SHARED,
    [PROGRESS_CHART_LATE]: PROGRESS_CHART__SHARED,
    [MARA_MEMENTO_POSTER]: [
        ALL_PEOPLE__SHARED,
        MARA
    ],
    [MARA_GLADIATOR_POSTER]: [
        POSTER_GLADIATOR__SHARED,
        ALL_PEOPLE__SHARED,
        MARA
    ],
    [GLADIATOR_POSTER]: [
        POSTER_GLADIATOR__SHARED,
        ALL_PEOPLE__SHARED
    ],
    [CODE_BOX]: null,
    [CLIPBOARD]: null,
    [PAINTING]: null,
    [NAS_ALBUM]: ALL_PEOPLE__SHARED,
    [ELLIOTT_SMITH_POSTER]: ALL_PEOPLE__SHARED,
    [SNOWGLOBE_PAST]: [
        SNOWGLOBE__SHARED,
        BENNETT,
        CHRISTOPHER,
        ALL_PEOPLE__SHARED
    ],
    [SNOWGLOBE_PRESENT]: [
        SNOWGLOBE__SHARED,
        BENNETT,
        LIZ,
        ALL_PEOPLE__SHARED
    ],
    [SNOWGLOBE_FUTURE_CORD]: [
        SNOWGLOBE__SHARED,
        BENNETT,
        ALL_PEOPLE__SHARED
    ],
    [SNOWGLOBE_FUTURE_REATTA]: [
        REATTA__SHARED,
        SNOWGLOBE__SHARED,
        BENNETT,
        MIRIAM,
        ALL_PEOPLE__SHARED
    ],

    [MARQUEE_FRAME]: null,
    [SNOWGLOBE_SMALL]: SNOWGLOBE__SHARED
}

