export const BEDROOM_FURNITURE__SHARED = 'bedroomFurniture'
export const BLANKET_HOSPITAL__SHARED = 'blanketHospital'
export const PILLOW_BENNETT__SHARED = 'pillowBennett'
export const PILLOW_LIZ__SHARED = 'pillowLiz'
export const PILLOW_PRETEEN_BENNETT__SHARED = 'pillowPreteenBennett'
export const PILLOW_BOYFRIEND__SHARED = 'pillowBoyfriend'
export const WAITING_ARMCHAIR__SHARED = 'waitingArmchair'
