export const HOSPITAL_LINENS__SHARED = 'hospitalLinens'
export const BENNETT_LINENS__SHARED = 'bennettLinens'
export const LIZ_LINENS__SHARED = 'lizLinens'
export const PRETEEN_FURNITURE__SHARED = 'preteenFurniture'
export const PRETEEN_LINENS__SHARED = 'preteenLinens'
export const WAITING_ARMCHAIR__SHARED = 'waitingArmchair'
