export const ACCESS_STORE = 'accessStore'
export const ACTIVATED_STORE = 'activatedStore'
export const ANNOTATION_STORE = 'annotationStore'
export const AUDIO_STORE = 'audioStore'
export const BANNER_STORE = 'bannerStore'
export const DOTS_STORE = 'dotsStore'
export const DOTS_SLIDE_STORE = 'dotsSlideStore'
export const ENTRANCE_STORE = 'entranceStore'
export const FOCUS_STORE = 'focusStore'
export const LYRIC_STORE = 'lyricStore'
export const OPTION_STORE = 'optionStore'
export const PLAYERS_STORE = 'playersStore'
export const SCENE_STORE = 'sceneStore'
export const SCROLL_CAROUSEL_STORE = 'scrollCarouselStore'
export const SCROLL_LYRIC_STORE = 'scrollLyricStore'
export const SCROLL_OVERLAY_STORE = 'scrollOverlayStore'
export const SELECTED_STORE = 'selectedStore'
export const SESSION_STORE = 'sessionStore'
export const SLIDER_STORE = 'sliderStore'
export const TOGGLE_STORE = 'toggleStore'
export const TRANSIENT_STORE = 'transientStore'
export const VERSE_BARS_STORE = 'verseBarsStore'
export const VIEWPORT_STORE = 'viewportStore'

export const IS_ACCESS_ON = 'isAccessOn'
export const IS_CAROUSEL_SHOWN = 'isCarouselShown'
export const SELECTED_DOTS_BIT = 'selectedDotsBit'

export const SELECTED_SONG_INDEX = 'selectedSongIndex'
export const SELECTED_VERSE_INDEX = 'selectedVerseIndex'
export const SELECTED_ANNOTATION_INDEX = 'selectedAnnotationIndex'

export const AUDIO_OPTION_INDEX = 'audioOptionIndex'
export const SELECTED_OVERVIEW_OPTION = 'selectedOverviewOption'
export const SELECTED_TIPS_OPTION = 'selectedTipsOption'
