export const FOLIAGE__SHARED = 'foliage'
export const FREEWAY_SIGN__SHARED = 'freewaySign'
export const GRAVE__SHARED = 'grave'
export const LAMPPOST__SHARED = 'lamppost'
export const MOUNTAIN__SHARED = 'mountain'
export const SHORE__SHARED = 'shore'
export const TETHERBALL_POLE__SHARED = 'tetherballPole'
export const TRASH_CAN__SHARED = 'trashCan'
