export const getHandlers = (me) => {
    const {
        setCarouselAnnotationRef,
        setLyricAnnotationRef,
        setVerseRef,
        setLyricVerseParentRef,
        setCarouselParentRef
    } = me.props

    return {
        focusElementForAccess: me.focusElementForAccess,
        handleAnnotationAccess: me.handleAnnotationAccess,
        handleAnnotationAnchorAccess: me.handleAnnotationAnchorAccess,
        handleVerseDirectionAccess: me.handleVerseDirectionAccess,
        handleBodyClick: me.handleBodyClick,
        handleBodyTouchMove: me.handleBodyTouchMove,
        handleBodyTouchEnd: me.handleBodyTouchEnd,
        handlePopupContainerClick: me.handlePopupContainerClick,
        handleAnnotationWormholeSelect: me.handleAnnotationWormholeSelect,
        handleAnnotationPrevious: me.handleAnnotationPrevious,
        handleAnnotationNext: me.handleAnnotationNext,
        handleAudioPlay: me.handleAudioPlay,
        handleAudioPreviousSong: me.handleAudioPreviousSong,
        handleAudioNextSong: me.handleAudioNextSong,
        handleSliderTouchBegin: me.handleSliderTouchBegin,
        handleLyricColumnSelect: me.handleLyricColumnSelect,
        handleLyricVerseSelect: me.handleLyricVerseSelect,
        handleLyricAnnotationSelect: me.handleLyricAnnotationSelect,
        handleLyricWheel: me.handleLyricWheel,
        handleLyricAutoScroll: me.handleLyricAutoScroll,
        handleNavSongSelect: me.handleNavSongSelect,
        handleNavBookSelect: me.handleNavBookSelect,
        handleOverviewToggle: me.handleOverviewToggle,
        handleCarouselNavToggle: me.handleCarouselNavToggle,
        handleSceneDirection: me.handleSceneDirection,
        handleTipsToggle: me.handleTipsToggle,
        handleVerseBarSelect: me.handleVerseBarSelect,
        handleVerseBarWheel: me.handleVerseBarWheel,
        handleVerseInteractivate: me.handleVerseInteractivate,
        handleScrollUponLyricRender: me.handleScrollUponLyricRender,
        handleScrollUponCarouselRender: me.handleScrollUponCarouselRender,
        stopPropagation: me.stopPropagation,
        setLyricRef: me.setLyricRef,
        setRootRef: me.setRootRef,
        setScoreRef: me.setScoreRef,
        setWikiRef: me.setWikiRef,
        setCarouselAnnotationRef,
        setLyricAnnotationRef,
        setVerseRef,
        setLyricVerseParentRef,
        setCarouselParentRef
    }
}
