import {
    BATHTUB,
    BEDROOM_DESK,
    CAPTAIN_BED,
    BEDROOM_FENCE,
    CAVE_SHADOWS,
    STALACTITES,
    TROLL_SHADOW_LEFT,
    TROLL_SHADOW_RIGHT,
    TROLL_SHADOW_FAR,
    TAIWAN_BRIDGE,
    SCHOOLBUS_INTERIOR,
    SCHOOLBUS_EXTERIOR,
    OCEAN_CAVE_INTERIOR,
    OCEAN_CAVE_EXTERIOR,
    CONVEYOR_BELT,
    DISHROOM_SINK,
    BENNETT_BED,
    LIZ_BED,
    SATURN_INTERIOR,
    SATURN_EXTERIOR,
    ATTIC_COUCH,
    VOLKSWAGEN,
    CROWD_SIDE,
    LIZ_COUCH,
    REATTA_INTERIOR,
    REATTA_SEAT,
    REATTA_SEAT_DOWN,
    REATTA_EXTERIOR,
    HOSPITAL_BED,
    PHONE_CALL_PANEL,
    CROWD_BACK,
    WEDDING_PLATFORM,

    TAIWAN_HAZE,
    SCHOOLBUS_SEAT,
    WIDE_COUCH,
    WIDE_ARMREST,
    GO_KART_SEAT,
    GO_KART_EXTERIOR,
    WAITING_ARMCHAIR,
    WAITING_ARMREST,
    SATURN_SEAT,
    ATTIC_ARMREST,
    SNOWGLOBE
} from '../../../../constants/scene/things/panels'

import { WEDDING__SHARED } from '../../../sharedStyles/buildings'
import {
    CUP__SHARED,
    DISH__SHARED,
    TRAY__SHARED
} from '../../../sharedStyles/dishroom'
import { WAITING_ARMCHAIR__SHARED } from '../../../sharedStyles/furniture'
import {
    SHADOW__SHARED,
    SNOWGLOBE__SHARED
} from '../../../sharedStyles/props'
import { BUDDHA_SHRINE__SHARED } from '../../../sharedStyles/taiwan'
import {
    INTERIOR__SHARED,
    REATTA__SHARED
} from '../../../sharedStyles/vehicles'

export default {
    [BATHTUB]: null,
    [BEDROOM_DESK]: null,
    [CAPTAIN_BED]: null,
    [BEDROOM_FENCE]: null,
    [CAVE_SHADOWS]: SHADOW__SHARED,
    [STALACTITES]: SHADOW__SHARED,
    [TROLL_SHADOW_LEFT]: SHADOW__SHARED,
    [TROLL_SHADOW_RIGHT]: SHADOW__SHARED,
    [TROLL_SHADOW_FAR]: SHADOW__SHARED,
    [TAIWAN_BRIDGE]: null,
    [SCHOOLBUS_INTERIOR]: INTERIOR__SHARED,
    [SCHOOLBUS_EXTERIOR]: null,
    [OCEAN_CAVE_INTERIOR]: BUDDHA_SHRINE__SHARED,
    [OCEAN_CAVE_EXTERIOR]: null,
    [CONVEYOR_BELT]: [
        CUP__SHARED,
        DISH__SHARED,
        TRAY__SHARED
    ],
    [DISHROOM_SINK]: null,
    [BENNETT_BED]: SHADOW__SHARED,
    [LIZ_BED]: SHADOW__SHARED,
    [SATURN_INTERIOR]: INTERIOR__SHARED,
    [SATURN_EXTERIOR]: null,
    [ATTIC_COUCH]: null,
    [VOLKSWAGEN]: null,
    [CROWD_SIDE]: SHADOW__SHARED,
    [LIZ_COUCH]: SHADOW__SHARED,
    [REATTA_INTERIOR]: INTERIOR__SHARED,
    [REATTA_SEAT]: null,
    [REATTA_SEAT_DOWN]: null,
    [REATTA_EXTERIOR]: REATTA__SHARED,
    [HOSPITAL_BED]: null,
    [PHONE_CALL_PANEL]: null,
    [CROWD_BACK]: SHADOW__SHARED,
    [WEDDING_PLATFORM]: WEDDING__SHARED,

    [TAIWAN_HAZE]: null,
    [SCHOOLBUS_SEAT]: null,
    [WIDE_COUCH]: null,
    [WIDE_ARMREST]: null,
    [GO_KART_SEAT]: null,
    [GO_KART_EXTERIOR]: null,
    [WAITING_ARMCHAIR]: WAITING_ARMCHAIR__SHARED,
    [WAITING_ARMREST]: WAITING_ARMCHAIR__SHARED,
    [SATURN_SEAT]: null,
    [ATTIC_ARMREST]: null,
    [SNOWGLOBE]: SNOWGLOBE__SHARED
}
