import {
    ATTIC_ARMREST,
    ATTIC_COUCH,
    BASEMENT_FENCE,
    BATHTUB,
    BEDROOM_DESK,
    BEDROOM_FENCE,
    BENNETT_BED,
    CAPTAIN_BED,
    CAVE_SHADOWS,
    CONVEYOR_BELT,
    CROWD_BACK,
    CROWD_SIDE,
    DISHROOM_SINK,
    GO_KART_EXTERIOR,
    GO_KART_SEAT,
    HOSPITAL_BED,
    LIZ_BED,
    LIZ_COUCH,
    OCEAN_CAVE_EXTERIOR,
    OCEAN_CAVE_INTERIOR,
    PHONE_CALL_PANEL,
    REATTA_EXTERIOR,
    REATTA_INTERIOR,
    REATTA_SEAT,
    REATTA_SEAT_DOWN,
    SATURN_EXTERIOR,
    SATURN_INTERIOR,
    SATURN_SEAT,
    SCHOOLBUS_EXTERIOR,
    SCHOOLBUS_INTERIOR,
    SCHOOLBUS_SEAT,
    SNOWGLOBE,
    STALACTITES,
    TAIWAN_BRIDGE,
    TAIWAN_HAZE,
    TROLL_SHADOW_FAR,
    TROLL_SHADOW_LEFT,
    TROLL_SHADOW_RIGHT,
    VOLKSWAGEN,
    WAITING_ARMCHAIR,
    WAITING_ARMREST,
    WEDDING_PLATFORM,
    WIDE_ARMREST,
    WIDE_COUCH
} from '../../../../constants/scene/things/panels'

import { OCEAN_LIFE__SHARED } from '../../../sharedStyles/animals'
import { WEDDING__SHARED } from '../../../sharedStyles/buildings'
import {
    CUP__SHARED,
    DISH__SHARED,
    TRAY__SHARED
} from '../../../sharedStyles/dishroom'
import {
    PRETEEN_FURNITURE__SHARED,
    WAITING_ARMCHAIR__SHARED
} from '../../../sharedStyles/furniture'
import {
    FOLIAGE__SHARED,
    MOUNTAIN__SHARED,
    OCEAN_CAVE__SHARED,
    ROCK__SHARED,
    WALL__SHARED
} from '../../../sharedStyles/outdoor'
import {
    SHADOW__SHARED,
    SNOWGLOBE__SHARED
} from '../../../sharedStyles/props'
import { BUDDHA_SHRINE__SHARED } from '../../../sharedStyles/taiwan'
import {
    ALL_VEHICLES__SHARED,
    INTERIOR__SHARED,
    REATTA__SHARED,
    SCHOOLBUS__SHARED
} from '../../../sharedStyles/vehicles'

export default {
    [ATTIC_ARMREST]: null,
    [ATTIC_COUCH]: null,
    [BASEMENT_FENCE]: [
        FOLIAGE__SHARED,
        WALL__SHARED
    ],
    [BATHTUB]: null,
    [BEDROOM_DESK]: PRETEEN_FURNITURE__SHARED,
    [BEDROOM_FENCE]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED,
        WALL__SHARED
    ],
    [BENNETT_BED]: SHADOW__SHARED,
    [CAPTAIN_BED]: PRETEEN_FURNITURE__SHARED,
    [CAVE_SHADOWS]: ROCK__SHARED,
    [CONVEYOR_BELT]: [
        CUP__SHARED,
        DISH__SHARED,
        TRAY__SHARED
    ],
    [CROWD_BACK]: SHADOW__SHARED,
    [CROWD_SIDE]: SHADOW__SHARED,
    [DISHROOM_SINK]: null,
    [GO_KART_EXTERIOR]: ALL_VEHICLES__SHARED,
    [GO_KART_SEAT]: null,
    [HOSPITAL_BED]: null,
    [LIZ_BED]: SHADOW__SHARED,
    [LIZ_COUCH]: SHADOW__SHARED,
    [OCEAN_CAVE_EXTERIOR]: OCEAN_CAVE__SHARED,
    [OCEAN_CAVE_INTERIOR]: [
        BUDDHA_SHRINE__SHARED,
        OCEAN_LIFE__SHARED,
        ROCK__SHARED
    ],
    [PHONE_CALL_PANEL]: null,
    [REATTA_EXTERIOR]: [
        ALL_VEHICLES__SHARED,
        REATTA__SHARED
    ],
    [REATTA_INTERIOR]: INTERIOR__SHARED,
    [REATTA_SEAT]: REATTA__SHARED,
    [REATTA_SEAT_DOWN]: REATTA__SHARED,
    [SATURN_EXTERIOR]: ALL_VEHICLES__SHARED,
    [SATURN_INTERIOR]: INTERIOR__SHARED,
    [SATURN_SEAT]: null,
    [SCHOOLBUS_EXTERIOR]: [
        ALL_VEHICLES__SHARED,
        SCHOOLBUS__SHARED
    ],
    [SCHOOLBUS_INTERIOR]: INTERIOR__SHARED,
    [SCHOOLBUS_SEAT]: null,
    [SNOWGLOBE]: SNOWGLOBE__SHARED,
    [STALACTITES]: SHADOW__SHARED,
    [TAIWAN_BRIDGE]: null,
    [TAIWAN_HAZE]: null,
    [TROLL_SHADOW_FAR]: SHADOW__SHARED,
    [TROLL_SHADOW_LEFT]: SHADOW__SHARED,
    [TROLL_SHADOW_RIGHT]: SHADOW__SHARED,
    [VOLKSWAGEN]: ALL_VEHICLES__SHARED,
    [WAITING_ARMCHAIR]: WAITING_ARMCHAIR__SHARED,
    [WAITING_ARMREST]: WAITING_ARMCHAIR__SHARED,
    [WEDDING_PLATFORM]: [
        FOLIAGE__SHARED,
        WEDDING__SHARED
    ],
    [WIDE_ARMREST]: null,
    [WIDE_COUCH]: null
}
