import {
    PUPPET_BENNETT_BEGIN,
    PUPPET_ANITA_BEGIN,
    PUPPET_CHRISTOPHER_BEGIN,
    PUPPET_FATHER_BEGIN,
    PUPPET_MOTHER_BEGIN,
    PUPPET_BENNETT_MIDDLE,
    PUPPET_ANITA_MIDDLE,
    PUPPET_CHRISTOPHER_MIDDLE,
    PUPPET_FATHER_MIDDLE,
    PUPPET_MOTHER_MIDDLE,
    PUPPET_BENNETT_END,
    PUPPET_ANITA_END,
    PUPPET_CHRISTOPHER_END,
    PUPPET_FATHER_END,
    PUPPET_MOTHER_END,
    OPAL_COUCH,
    OPAL_GAZING,
    PEACOCK,
    PEAHEN,
    PUPPET_REATTA,
    GHOST_ODIN_CAMPUS,
    GHOST_ODIN_CLUB,
    GHOST_ODIN_ALLEY,
    GHOST_ODIN_DEMONSTRATION,
    PUPPET_KHARI_LIZ
} from '../../../../constants/scene/things/puppets'

import {
    ANITA,
    BENNETT,
    CHRISTOPHER,
    FATHER,
    MIRIAM,
    MOTHER
} from '../../../../constants/scene/actors'
import { ALL_PEOPLE__SHARED } from '../../../sharedStyles/people'
import {
    ODIN_GHOST__SHARED,
    OPAL__SHARED,
    PEAFOWL__SHARED
} from '../../../sharedStyles/animals'
import { SKETCHBOOK__SHARED } from '../../../sharedStyles/sketch'
import { REATTA__SHARED } from '../../../sharedStyles/vehicles'
export default {
    [PUPPET_BENNETT_BEGIN]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        SKETCHBOOK__SHARED
    ],
    [PUPPET_ANITA_BEGIN]: [
        ALL_PEOPLE__SHARED,
        ANITA
    ],
    [PUPPET_CHRISTOPHER_BEGIN]: [
        ALL_PEOPLE__SHARED,
        CHRISTOPHER
    ],
    [PUPPET_FATHER_BEGIN]: [
        ALL_PEOPLE__SHARED,
        FATHER
    ],
    [PUPPET_MOTHER_BEGIN]: [
        ALL_PEOPLE__SHARED,
        MOTHER
    ],
    [PUPPET_BENNETT_MIDDLE]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        SKETCHBOOK__SHARED
    ],
    [PUPPET_ANITA_MIDDLE]: [
        ALL_PEOPLE__SHARED,
        ANITA
    ],
    [PUPPET_CHRISTOPHER_MIDDLE]: [
        ALL_PEOPLE__SHARED,
        CHRISTOPHER
    ],
    [PUPPET_FATHER_MIDDLE]: [
        ALL_PEOPLE__SHARED,
        FATHER
    ],
    [PUPPET_MOTHER_MIDDLE]: [
        ALL_PEOPLE__SHARED,
        MOTHER
    ],
    [PUPPET_BENNETT_END]: [
        ALL_PEOPLE__SHARED,
        BENNETT,
        SKETCHBOOK__SHARED
    ],
    [PUPPET_ANITA_END]: [
        ALL_PEOPLE__SHARED,
        ANITA
    ],
    [PUPPET_CHRISTOPHER_END]: [
        ALL_PEOPLE__SHARED,
        CHRISTOPHER
    ],
    [PUPPET_FATHER_END]: [
        ALL_PEOPLE__SHARED,
        FATHER
    ],
    [PUPPET_MOTHER_END]: [
        ALL_PEOPLE__SHARED,
        MOTHER
    ],
    [OPAL_COUCH]: OPAL__SHARED,
    [OPAL_GAZING]: OPAL__SHARED,
    [PEACOCK]: PEAFOWL__SHARED,
    [PEAHEN]: PEAFOWL__SHARED,
    [PUPPET_REATTA]: [
        REATTA__SHARED,
        ALL_PEOPLE__SHARED,
        BENNETT,
        MIRIAM
    ],
    [GHOST_ODIN_CAMPUS]: ODIN_GHOST__SHARED,
    [GHOST_ODIN_CLUB]: ODIN_GHOST__SHARED,
    [GHOST_ODIN_ALLEY]: ODIN_GHOST__SHARED,
    [GHOST_ODIN_DEMONSTRATION]: ODIN_GHOST__SHARED,
    [PUPPET_KHARI_LIZ]: ALL_PEOPLE__SHARED
}
