const
    BREAKUP_DEJECTED = 'breakupDejected',
    SOLICITING_OPINION = 'solicitingOpinion',
    CATHOLIC_PENSIVE = 'catholicPensive',
    CATHOLIC_IDEA = 'catholicIdea',
    PIOUS = 'pious',
    PONDERING = 'pondering',
    COUCH_READING = 'couchReading',
    RUBIKS_CUBE = 'rubiksCube',
    DISTRACTED = 'distracted',
    HOPELESSLY_CRUSHED = 'hopelesslyCrushed',
    WONDERING_BABY = 'wonderingBaby',
    MERRILY_DERANGED = 'merrilyDeranged',
    DISHROOM_READING = 'dishroomReading',
    MOP_SOPPED = 'mopSopped',
    WAITING_ROOM_ASLEEP = 'waitingRoomAsleep',
    SIDELONG_HESITANCE = 'sidelongHesitance',
    REMOVING_SHOES = 'removingShoes',
    SHOES_REFLECTION = 'shoesReflection',
    DROPPING_MEATS = 'droppingMeats',
    CORD_SIDE = 'cordSide',
    CORD_REAR = 'cordRear',
    REMOVING_PANTS = 'removingPants',
    INFIRM = 'infirm',
    DISPOSING_CONDOM = 'disposingCondom',
    CAMPUS_ASHAMED = 'campusAshamed',
    SHOW_ANNOYED = 'showAnnoyed',
    ALLEY = 'alley',
    BROKEN_HEARTED = 'brokenHearted',
    DEMONSTRATION = 'demonstration'

export {
    BREAKUP_DEJECTED,
    SOLICITING_OPINION,
    CATHOLIC_PENSIVE,
    CATHOLIC_IDEA,
    PIOUS,
    PONDERING,
    COUCH_READING,
    RUBIKS_CUBE,
    DISTRACTED,
    HOPELESSLY_CRUSHED,
    WONDERING_BABY,
    MERRILY_DERANGED,
    DISHROOM_READING,
    MOP_SOPPED,
    WAITING_ROOM_ASLEEP,
    SIDELONG_HESITANCE,
    REMOVING_SHOES,
    SHOES_REFLECTION,
    DROPPING_MEATS,
    CORD_SIDE,
    CORD_REAR,
    REMOVING_PANTS,
    INFIRM,
    DISPOSING_CONDOM,
    CAMPUS_ASHAMED,
    SHOW_ANNOYED,
    ALLEY,
    BROKEN_HEARTED,
    DEMONSTRATION
}
