const
    CAUTIOUS = 'cautious',
    ENRAGED = 'enraged',
    FEARFUL = 'fearful',
    PANICKED = 'panicked',
    MAT = 'mat',
    STAIRS = 'stairs',
    GATE = 'gate',
    RICKSHAW = 'rickshaw',
    SHORE = 'shore',
    BUOY = 'buoy',
    OCEAN_FLOOR = 'oceanFloor',
    FEIGNING_SICK = 'feigningSick',
    ASLEEP = 'asleep',
    SHAKEN = 'shaken',
    STOIC = 'stoic',
    WISTFUL = 'wistful',
    SHEEPISH = 'sheepish'

export {
    CAUTIOUS,
    ENRAGED,
    FEARFUL,
    PANICKED,
    MAT,
    STAIRS,
    GATE,
    RICKSHAW,
    SHORE,
    BUOY,
    OCEAN_FLOOR,
    FEIGNING_SICK,
    ASLEEP,
    SHAKEN,
    STOIC,
    WISTFUL,
    SHEEPISH
}
