export const BENNETT_GATE__SHARED = 'bennettGate'
export const DOOR__SHARED = 'door'
export const LIZ_GATE__SHARED = 'lizGate'
export const TAIWAN_GATE__SHARED = 'taiwanGate'
export const WINDOW__SHARED = 'window'
