import {

    DEVICE_INDEX,
    WINDOW_HEIGHT,
    WINDOW_WIDTH,
    STAGE_COORDINATES,
    STAGE_COORDINATES_DEFAULT,

    IS_SLIDER_MOVING,
    IS_SLIDER_TOUCHED,
    SLIDER_LEFT,
    SLIDER_RATIO,
    SLIDER_WIDTH,
    SLIDER_VERSE_INDEX

} from '../constants/state'

export const DEVICE_DEFAULTS = {
    [DEVICE_INDEX]: 0,
    [WINDOW_HEIGHT]: 0,
    [WINDOW_WIDTH]: 0,
    [STAGE_COORDINATES]: STAGE_COORDINATES_DEFAULT
}

export const SLIDER_DEFAULTS = {
    [IS_SLIDER_MOVING]: false,
    [IS_SLIDER_TOUCHED]: false,
    [SLIDER_LEFT]: 0,
    [SLIDER_RATIO]: 0,
    [SLIDER_WIDTH]: 0,
    [SLIDER_VERSE_INDEX]: -1
}
