export const ACCESS_STORE = 'accessStore'
export const ANNOTATION_STORE = 'annotationStore'
export const AUDIO_STORE = 'audioStore'
export const CHANGE_STORE = 'changeStore'
export const CURTAIN_STORE = 'curtainStore'
export const DEVICE_STORE = 'deviceStore'
export const DOTS_STORE = 'dotsStore'
export const FOCUS_STORE = 'focusStore'
export const LOAD_STORE = 'loadStore'
export const OPTION_STORE = 'optionStore'
export const PLAYERS_STORE = 'playersStore'
export const RENDER_STORE = 'renderStore'
export const RENDERED_STORE = 'renderedStore'
export const RESPONSIVE_STORE = 'responsiveStore'
export const SCENE_STORE = 'sceneStore'
export const SCROLL_CAROUSEL_STORE = 'scrollCarouselStore'
export const SCROLL_LYRIC_STORE = 'scrollLyricStore'
export const SELECTED_STORE = 'selectedStore'
export const SESSION_STORE = 'sessionStore'
export const SLIDER_STORE = 'sliderStore'
export const TOGGLE_STORE = 'toggleStore'
export const TRANSIENT_STORE = 'transientStore'
export const VERSE_BARS_STORE = 'verseBarsStore'

export const IS_ACCESS_ON = 'isAccessOn'
export const IS_ADMIN_ON = 'isAdminOn'
export const IS_CAROUSEL_SHOWN = 'isCarouselShown'
export const SELECTED_DOT_KEYS = 'selectedDotKeys'

export const SELECTED_SONG_INDEX = 'selectedSongIndex'
export const SELECTED_VERSE_INDEX = 'selectedVerseIndex'
export const SELECTED_ANNOTATION_INDEX = 'selectedAnnotationIndex'

export const SELECTED_AUDIO_OPTION_INDEX = 'selectedAudioOptionIndex'
export const SELECTED_EAR_COLUMN_INDEX = 'earColumnIndex'
export const SELECTED_OVERVIEW_OPTION = 'selectedOverviewOption'
export const SELECTED_TIPS_OPTION = 'selectedTipsOption'
