module.exports = {
    ACCESS_STORE: 'accessStore',
    ANNOTATION_STORE: 'annotationStore',
    AUDIO_STORE: 'audioStore',
    DEVICE_STORE: 'deviceStore',
    DOTS_STORE: 'dotsStore',
    EVENT_STORE: 'eventStore',
    LOAD_STORE: 'loadStore',
    OPTION_STORE: 'optionStore',
    PLAYERS_STORE: 'playersStore',
    RENDER_STORE: 'renderStore',
    RENDERABLE_STORE: 'renderableStore',
    RENDERED_STORE: 'renderedStore',
    RESPONSIVE_STORE: 'responsiveStore',
    SCENE_STORE: 'sceneStore',
    SCROLL_CAROUSEL_STORE: 'scrollCarouselStore',
    SCROLL_LYRIC_STORE: 'scrollLyricStore',
    SESSION_STORE: 'sessionStore',
    SLIDER_STORE: 'sliderStore',
    SONG_STORE: 'songStore',
    TOGGLE_STORE: 'toggleStore',
    TRANSIENT_STORE: 'transientStore',
    VERSE_BARS_STORE: 'verseBarsStore',

    IS_ACCESS_ON: 'isAccessOn',
    IS_ADMIN_ON: 'isAdminOn',
    IS_CAROUSEL_SHOWN: 'isCarouselShown',
    SELECTED_DOT_KEYS: 'selectedDotKeys',

    SELECTED_SONG_INDEX: 'selectedSongIndex',
    SELECTED_VERSE_INDEX: 'selectedVerseIndex',
    SELECTED_ANNOTATION_INDEX: 'selectedAnnotationIndex',

    SELECTED_AUDIO_OPTION_INDEX: 'selectedAudioOptionIndex',
    SELECTED_EAR_COLUMN_INDEX: 'earColumnIndex',
    SELECTED_OVERVIEW_OPTION: 'selectedOverviewOption',
    SELECTED_TIPS_OPTION: 'selectedTipsOption'
}
