import {
    PRETEEN_BENNETT,
    BENNETTS_CHRISTOPHER_LIZ,
    OLD_BENNETT,
    ANITA_BENNETT,
    ESTHER,
    WILLY,
    MOTHER,
    FATHER,
    SASHA,
    BRAD,
    ANDREW,
    CATHERINE,
    MARA,
    JACOB,
    ANA,
    HOWIE,
    TOMER,
    KHARI,
    MIRIAM,
    TRISTAN,
    NESTOR,
    AMY,
    STEPHANIE,
    WADE
} from '../../actorKeys'

import ARRANGEMENTS_PRETEEN_BENNETT from './actors/preteenBennett'
import ARRANGEMENTS_BENNETTS_CHRISTOPHER_LIZ from './actors/bennettsChristopherLiz'
import ARRANGEMENTS_OLD_BENNETT from './actors/oldBennett'
import ARRANGEMENTS_ANITA_BENNETT from './actors/anitaBennett'
import ARRANGEMENTS_ESTHER from './actors/esther'
import ARRANGEMENTS_WILLY from './actors/willy'
import ARRANGEMENTS_MOTHER from './actors/mother'
import ARRANGEMENTS_FATHER from './actors/father'
import ARRANGEMENTS_SASHA from './actors/sasha'
import ARRANGEMENTS_BRAD from './actors/brad'
import ARRANGEMENTS_ANDREW from './actors/andrew'
import ARRANGEMENTS_CATHERINE from './actors/catherine'
import ARRANGEMENTS_MARA from './actors/mara'
import ARRANGEMENTS_JACOB from './actors/jacob'
import ARRANGEMENTS_ANA from './actors/ana'
import ARRANGEMENTS_HOWIE from './actors/howie'
import ARRANGEMENTS_TOMER from './actors/tomer'
import ARRANGEMENTS_KHARI from './actors/khari'
import ARRANGEMENTS_MIRIAM from './actors/miriam'
import ARRANGEMENTS_TRISTAN from './actors/tristan'
import ARRANGEMENTS_NESTOR from './actors/nestor'
import ARRANGEMENTS_AMY from './actors/amy'
import ARRANGEMENTS_STEPHANIE from './actors/stephanie'
import ARRANGEMENTS_WADE from './actors/wade'

const ARRANGEMENTS_ACTORS = {
    [PRETEEN_BENNETT]: ARRANGEMENTS_PRETEEN_BENNETT,
    [BENNETTS_CHRISTOPHER_LIZ]: ARRANGEMENTS_BENNETTS_CHRISTOPHER_LIZ,
    [OLD_BENNETT]: ARRANGEMENTS_OLD_BENNETT,
    [ANITA_BENNETT]: ARRANGEMENTS_ANITA_BENNETT,
    [ESTHER]: ARRANGEMENTS_ESTHER,
    [WILLY]: ARRANGEMENTS_WILLY,
    [MOTHER]: ARRANGEMENTS_MOTHER,
    [FATHER]: ARRANGEMENTS_FATHER,
    [SASHA]: ARRANGEMENTS_SASHA,
    [BRAD]: ARRANGEMENTS_BRAD,
    [ANDREW]: ARRANGEMENTS_ANDREW,
    [CATHERINE]: ARRANGEMENTS_CATHERINE,
    [MARA]: ARRANGEMENTS_MARA,
    [JACOB]: ARRANGEMENTS_JACOB,
    [ANA]: ARRANGEMENTS_ANA,
    [HOWIE]: ARRANGEMENTS_HOWIE,
    [TOMER]: ARRANGEMENTS_TOMER,
    [KHARI]: ARRANGEMENTS_KHARI,
    [MIRIAM]: ARRANGEMENTS_MIRIAM,
    [TRISTAN]: ARRANGEMENTS_TRISTAN,
    [NESTOR]: ARRANGEMENTS_NESTOR,
    [AMY]: ARRANGEMENTS_AMY,
    [STEPHANIE]: ARRANGEMENTS_STEPHANIE,
    [WADE]: ARRANGEMENTS_WADE
}

export default ARRANGEMENTS_ACTORS
