import {
    CHRISTOPHER_BENNETT_WILLY
} from '../../keys'

import ARRANGEMENTS_CHRISTOPHER_BENNETT_WILLY from './actors/christopherBennettWilly'

const ARRANGEMENTS_ACTORS = {
    [CHRISTOPHER_BENNETT_WILLY]: ARRANGEMENTS_CHRISTOPHER_BENNETT_WILLY
}

export default ARRANGEMENTS_ACTORS
