export const BULB__SHARED = 'bulb'
export const FRIDGE__SHARED = 'fridge'
export const LIZ_PHONE__SHARED = 'lizPhone'
export const RUBIKS_CUBE__SHARED = 'rubiksCube'
export const SCISSORS__SHARED = 'scissors'
