export const BERKELEY_BUILDING__SHARED = 'berkeleyBuilding__shared'
export const OAKLAND_HOUSE__SHARED = 'oaklandHouse__shared'
export const OAKLAND_HOUSE_LEFT__SHARED = 'oaklandHouseLeft__shared'
export const OAKLAND_HOUSE_RIGHT__SHARED = 'oaklandHouseRight__shared'
export const OAKLAND_COMMERCIAL__SHARED = 'oaklandCommercial__shared'
export const TAIWAN_HOUSE__SHARED = 'taiwanHouse__shared'
