export const BACKPACK__SHARED = 'backpack'
export const BRACELET__SHARED = 'bracelet'
export const CHINESE__SHARED = 'chinese'
export const GHOST__SHARED = 'ghost'
export const LIZ_PURSE__SHARED = 'lizPurse'
export const SARI__SHARED = 'sari'
