import {
    DISTANT_BUILDINGS_BACKDROP,
    DISTANT_HOUSES_BACKDROP,
    DRIVING_BACKDROP,
    GOLDEN_GATE_BACKDROP,
    LOS_ANGELES_BACKDROP,
    MOUNTAIN_TAIWAN_BACKDROP,
    MOUNTAIN_PAMPAS_BACKDROP,
    NEAR_BUILDINGS,
    NEAR_HOUSES,
    OAKLAND_FRONT,
    OAKLAND_SIDE,
    OCEAN_BOTTOM_FAR,
    OCEAN_FLOOR_FAR,
    ROAD_FUTURE,
    ROAD_PAST,
    ROAD_PRESENT,
    SHORE_BUOY_BACKDROP,
    SHORE_RICKSHAW_BACKDROP,
    TAIWAN_MOUNTAINS_BACKDROP,
    TAIWAN_STAIRS_BACKDROP,
    VALLEY_CLOSER_BACKDROP,
    VALLEY_FURTHER_BACKDROP,
    VALLEY_PANORAMA_BACKDROP,
    WEDDING_BACKDROP
} from '../../../../constants/scene/things/backdrops'
import {
    BUILDINGS__SHARED,
    HOUSE__SHARED,
    TAIWAN_HOUSE__SHARED
} from '../../../../constants/scene/sharedStyles/buildings'
import { BOOK__SHARED } from '../../../../constants/scene/sharedStyles/paper'
import {
    FOLIAGE__SHARED,
    MOUNTAIN__SHARED,
    ROAD__SHARED,
    SHORE__SHARED,
    TAIWAN_FOLIAGE__SHARED,
    TAIWAN_MOUNTAIN__SHARED,
    VOLCANO__SHARED,
    WALL__SHARED
} from '../../../../constants/scene/sharedStyles/outdoor'

export default {
    [DISTANT_BUILDINGS_BACKDROP]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        WALL__SHARED
    ],
    [DISTANT_HOUSES_BACKDROP]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        WALL__SHARED
    ],
    [DRIVING_BACKDROP]: FOLIAGE__SHARED,
    [GOLDEN_GATE_BACKDROP]: [
        BUILDINGS__SHARED,
        MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [LOS_ANGELES_BACKDROP]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [MOUNTAIN_TAIWAN_BACKDROP]: TAIWAN_MOUNTAIN__SHARED,
    [MOUNTAIN_PAMPAS_BACKDROP]: MOUNTAIN__SHARED,
    [NEAR_BUILDINGS]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        WALL__SHARED
    ],
    [NEAR_HOUSES]: [
        FOLIAGE__SHARED,
        HOUSE__SHARED,
        WALL__SHARED
    ],
    [OAKLAND_FRONT]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [OAKLAND_SIDE]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [OCEAN_BOTTOM_FAR]: VOLCANO__SHARED,
    [OCEAN_FLOOR_FAR]: VOLCANO__SHARED,
    [ROAD_FUTURE]: ROAD__SHARED,
    [ROAD_PAST]: [
        BOOK__SHARED,
        ROAD__SHARED
    ],
    [ROAD_PRESENT]: ROAD__SHARED,
    [SHORE_BUOY_BACKDROP]: [
        TAIWAN_FOLIAGE__SHARED,
        TAIWAN_MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [SHORE_RICKSHAW_BACKDROP]: [
        TAIWAN_FOLIAGE__SHARED,
        TAIWAN_MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [TAIWAN_MOUNTAINS_BACKDROP]: TAIWAN_MOUNTAIN__SHARED,
    [TAIWAN_STAIRS_BACKDROP]: [
        TAIWAN_FOLIAGE__SHARED,
        TAIWAN_MOUNTAIN__SHARED,
        TAIWAN_HOUSE__SHARED
    ],
    [VALLEY_CLOSER_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [VALLEY_FURTHER_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [VALLEY_PANORAMA_BACKDROP]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [WEDDING_BACKDROP]: MOUNTAIN__SHARED
}
