const
    BREAKUP_DEJECTED = 'breakupDejected',
    SOLICITING_OPINION = 'solicitingOpinion',
    CATHOLIC_PENSIVE = 'catholicPensive',
    CATHOLIC_IDEA = 'catholicIdea',
    PIOUS = 'pious',
    PONDERING = 'pondering',
    COUCH_READING = 'couchReading',
    RUBIKS_CUBE = 'rubiksCube',
    DISTRACTED = 'distracted',
    HOPELESSLY_CRUSHED = 'hopelesslyCrushed',
    WONDERING_BABY = 'wonderingBaby',
    MERRILY_DERANGED = 'merrilyDeranged',
    DISHROOM_READING = 'dishroomReading',
    MOP_SOPPED = 'mopSopped',
    WAITING_ROOM_THOUGHTS = 'waitingRoomThoughts'

export {
    BREAKUP_DEJECTED,
    SOLICITING_OPINION,
    CATHOLIC_PENSIVE,
    CATHOLIC_IDEA,
    PIOUS,
    PONDERING,
    COUCH_READING,
    RUBIKS_CUBE,
    DISTRACTED,
    HOPELESSLY_CRUSHED,
    WONDERING_BABY,
    MERRILY_DERANGED,
    DISHROOM_READING,
    MOP_SOPPED,
    WAITING_ROOM_THOUGHTS,
}
