const
    ASLEEP_REACHING = 'asleepReaching',
    REACHING_REFLECTION = 'reachingReflection',
    BRUSHED_OFF = 'brushedOff',
    FREEZING_NAKED = 'freezingNaked',
    RETURNING_CORD = 'returningCord',
    PETTING_STANDING = 'pettingStanding',
    SIFTING_TCHOTCHKES = 'siftingTchotchkes',
    OPENING_DOOR = 'openingDoor',
    DEFENDING = 'defending',
    NOT_HUNGRY = 'notHungry',
    ASLEEP_COUCH = 'asleepCouch',
    PETTING_SEATED = 'pettingSeated',
    LAUGHING = 'laughing',
    SELFLESS_CONCERN = 'selflessConcern',
    CARESSED = 'beingCaressed',
    CARESSED_REFLECTION = 'caressedReflection'

export {
    ASLEEP_REACHING,
    REACHING_REFLECTION,
    BRUSHED_OFF,
    FREEZING_NAKED,
    RETURNING_CORD,
    PETTING_STANDING,
    SIFTING_TCHOTCHKES,
    OPENING_DOOR,
    DEFENDING,
    NOT_HUNGRY,
    ASLEEP_COUCH,
    PETTING_SEATED,
    LAUGHING,
    SELFLESS_CONCERN,
    CARESSED,
    CARESSED_REFLECTION,
}
