import {
    PRETEEN_BENNETT,
    MOTHER,
    FATHER,
    CHRISTOPHER,
    CHRISTOPHER_BENNETT
} from '../../actorKeys'

import ARRANGEMENTS_PRETEEN_BENNETT from './actors/preteenBennett'
import ARRANGEMENTS_MOTHER from './actors/mother'
import ARRANGEMENTS_FATHER from './actors/father'
import ARRANGEMENTS_CHRISTOPHER from './actors/christopher'
import ARRANGEMENTS_CHRISTOPHER_BENNETT from './actors/christopherBennett'

const ARRANGEMENTS_ACTORS = {
    [PRETEEN_BENNETT]: ARRANGEMENTS_PRETEEN_BENNETT,
    [MOTHER]: ARRANGEMENTS_MOTHER,
    [FATHER]: ARRANGEMENTS_FATHER,
    [CHRISTOPHER]: ARRANGEMENTS_CHRISTOPHER,
    [CHRISTOPHER_BENNETT]: ARRANGEMENTS_CHRISTOPHER_BENNETT
}

export default ARRANGEMENTS_ACTORS
