export const ACTOR = 'actor'

export const ACTOR_DEFAULT_SCALE_FACTOR = 0.25
export const BUBBLE_DEFAULT_SCALE_FACTOR = 0.4
export const DOOR_DEFAULT_SCALE_FACTOR = 0.7
export const FIXTURE_DEFAULT_SCALE_FACTOR = 0.3
export const FURNITURE_DEFAULT_SCALE_FACTOR = 0.25
