import {
    YOUNG_BENNETT,
    PRETEEN_BENNETT,
    BENNETT,
    BENNETT_FATHER,
    BENNETT_LIZ,
    BENNETT_LIZ_REFLECTION,
    BENNETTS_CHRISTOPHER_LIZ,
    BENNETT_STEPHANIE,
    OLD_BENNETT,
    ANITA,
    ANITA_BENNETT,
    ESTHER,
    ESTHER_MOTHER,
    WILLY,
    MOTHER,
    FATHER,
    CHRISTOPHER,
    CHRISTOPHER_BENNETT,
    CHRISTOPHER_BENNETT_WILLY,
    SASHA,
    SASHA_BENNETT,
    BRAD,
    BRAD_BENNETT,
    BRAD_SASHA,
    ANDREW,
    CATHERINE,
    MARA,
    JACOB,
    JACOB_MARA,
    ANA,
    ANA_HOWIE,
    HOWIE,
    HOWIE_WILLY,
    TOMER,
    LIZ,
    KHARI,
    KHARI_LIZ,
    MIRIAM,
    MIRIAM_BENNETT,
    MIRIAM_STEPHANIE,
    MIRIAM_TRISTAN,
    TRISTAN,
    NESTOR,
    AMY,
    AMY_STEPHANIE,
    AMY_NESTOR_TOMER,
    STEPHANIE,
    WADE,
    BENNETT_REFLECTION,
    LIZ_REFLECTION,
    KHARI_LIZ_REFLECTION
} from 'constants/scene/actors'

export default {
    [YOUNG_BENNETT]: false,
    [PRETEEN_BENNETT]: false,
    [BENNETT]: false,
    [BENNETT_FATHER]: false,
    [BENNETT_LIZ]: false,
    [BENNETT_LIZ_REFLECTION]: false,
    [BENNETTS_CHRISTOPHER_LIZ]: false,
    [BENNETT_STEPHANIE]: false,
    [OLD_BENNETT]: false,
    [ANITA]: false,
    [ANITA_BENNETT]: false,
    [ESTHER]: false,
    [ESTHER_MOTHER]: false,
    [WILLY]: false,
    [MOTHER]: false,
    [FATHER]: false,
    [CHRISTOPHER]: false,
    [CHRISTOPHER_BENNETT]: false,
    [CHRISTOPHER_BENNETT_WILLY]: false,
    [SASHA]: false,
    [SASHA_BENNETT]: false,
    [BRAD]: false,
    [BRAD_BENNETT]: false,
    [BRAD_SASHA]: false,
    [ANDREW]: false,
    [CATHERINE]: false,
    [MARA]: false,
    [JACOB]: false,
    [JACOB_MARA]: false,
    [ANA]: false,
    [ANA_HOWIE]: false,
    [HOWIE]: false,
    [HOWIE_WILLY]: false,
    [TOMER]: false,
    [LIZ]: false,
    [KHARI]: false,
    [KHARI_LIZ]: false,
    [MIRIAM]: false,
    [MIRIAM_BENNETT]: false,
    [MIRIAM_STEPHANIE]: false,
    [MIRIAM_TRISTAN]: false,
    [TRISTAN]: false,
    [NESTOR]: false,
    [AMY]: false,
    [AMY_STEPHANIE]: false,
    [AMY_NESTOR_TOMER]: false,
    [STEPHANIE]: false,
    [WADE]: false,
    [BENNETT_REFLECTION]: false,
    [LIZ_REFLECTION]: false,
    [KHARI_LIZ_REFLECTION]: false
}
