import {
    BRICK_WALL,
    DISTANT_BUILDINGS_BACKDROP,
    DISTANT_HOUSES_BACKDROP,
    DRIVING_BACKDROP,
    FENCE_BACKDROP,
    GOLDEN_GATE_BACKDROP,
    LOS_ANGELES_BACKDROP,
    MOUNTAIN_BACKDROP,
    OAKLAND_FRONT,
    OAKLAND_SIDE,
    OCEAN_BOTTOM_FAR,
    OCEAN_FLOOR_FAR,
    ROAD_FUTURE,
    ROAD_PAST,
    ROAD_PRESENT,
    SHORE_BUOY_BACKDROP,
    SHORE_RICKSHAW_BACKDROP,
    TAIWAN_MOUNTAINS_BACKDROP,
    TAIWAN_STAIRS_BACKDROP,
    VALLEY_CLOSER_BACKDROP,
    VALLEY_FURTHER_BACKDROP,
    VALLEY_PANORAMA_BACKDROP,
    WEDDING_BACKDROP,
    YARD_BACKDROP
} from '../../../../constants/scene/things/backdrops'

import {
    BUILDINGS__SHARED,
    DISTANT__SHARED,
    TAIWAN_HOUSE__SHARED
} from '../../../sharedStyles/buildings'
import { BOOK__SHARED } from '../../../sharedStyles/paper'
import {
    FOLIAGE__SHARED,
    MOUNTAIN__SHARED,
    SHORE__SHARED
} from '../../../sharedStyles/outdoor'
import { ROAD__SHARED } from '../../../sharedStyles/props'

export default {
    [BRICK_WALL]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED
    ],
    [DISTANT_BUILDINGS_BACKDROP]: [
        BUILDINGS__SHARED,
        DISTANT__SHARED,
        FOLIAGE__SHARED
    ],
    [DISTANT_HOUSES_BACKDROP]: [
        DISTANT__SHARED,
        FOLIAGE__SHARED
    ],
    [DRIVING_BACKDROP]: FOLIAGE__SHARED,
    [FENCE_BACKDROP]: FOLIAGE__SHARED,
    [GOLDEN_GATE_BACKDROP]: [
        BUILDINGS__SHARED,
        MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [LOS_ANGELES_BACKDROP]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [MOUNTAIN_BACKDROP]: MOUNTAIN__SHARED,
    [OAKLAND_FRONT]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [OAKLAND_SIDE]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [OCEAN_BOTTOM_FAR]: null,
    [OCEAN_FLOOR_FAR]: null,
    [ROAD_FUTURE]: ROAD__SHARED,
    [ROAD_PAST]: [
        BOOK__SHARED,
        ROAD__SHARED
    ],
    [ROAD_PRESENT]: ROAD__SHARED,
    [SHORE_BUOY_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [SHORE_RICKSHAW_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED,
        SHORE__SHARED
    ],
    [TAIWAN_MOUNTAINS_BACKDROP]: MOUNTAIN__SHARED,
    [TAIWAN_STAIRS_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED,
        TAIWAN_HOUSE__SHARED
    ],
    [VALLEY_CLOSER_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [VALLEY_FURTHER_BACKDROP]: [
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [VALLEY_PANORAMA_BACKDROP]: [
        BUILDINGS__SHARED,
        FOLIAGE__SHARED,
        MOUNTAIN__SHARED
    ],
    [WEDDING_BACKDROP]: MOUNTAIN__SHARED,
    [YARD_BACKDROP]: FOLIAGE__SHARED
}
